//! LMS (SP 800-208) — Leighton-Micali stateful hash-based signatures.
//!
//! Implements the LMS / LM-OTS family from RFC 8554 and RFC 8708,
//! approved for FIPS use by SP 800-208. LMS is a **stateful** scheme:
//! each Merkle-tree leaf may be used to sign exactly one message. The
//! signer must persist the private key's `leaf_index` after every
//! signature to prevent catastrophic one-time-key reuse. Each
//! parameter-set instantiation enforces the state counter and refuses
//! to sign once the tree is exhausted.
//!
//! # Architecture — `lms_impl!` macro
//!
//! Every (LMS, LM-OTS) parameter pair is generated by the
//! [`lms_impl!`](lms_impl::lms_impl) macro from one parameter tuple. A
//! per-pair `lms_<family>_m<N>_h<H>_w<W>` module invokes the macro and
//! emits a full self-contained implementation — keygen, sign, verify,
//! the LM-OTS one-time-signature internals, the Merkle-tree traversal,
//! and the power-up KAT — for that pair only.
//!
//! Family-and-`N` divergence (SHA-256 / SHAKE-256, output length 24 or
//! 32) is realised by a hash-adapter `:path` captured into the macro,
//! one concrete adapter per (family, N) shape in [`hash`]. There is no
//! nested sub-macro that dispatches on a `:literal` hash-family token,
//! per the macro-audit-triage rule.
//!
//! # Approved services
//!
//! Each (LMS, LM-OTS) pair declares two `oxicrypt_module::Service`
//! discriminants — one for sign, one for verify — in the per-pair
//! convention `Lms<Family>M<N>H<H>W<W>{Sign,Verify}`. The 80-pair grid
//! occupies discriminants 500-659 (Sign + Verify alternating per pair).
//!
//! | Service group | Standard | Discriminant range |
//! |---|---|---|
//! | SHA-256 / N=32 (20 pairs × 2 ops) | RFC 8554 §A.1+§A.2 | 500-539 |
//! | SHA-256 / N=24 (20 pairs × 2 ops) | RFC 8708 §4.1 | 540-579 |
//! | SHAKE-256 / N=32 (20 pairs × 2 ops) | RFC 8708 §3.1 | 580-619 |
//! | SHAKE-256 / N=24 (20 pairs × 2 ops) | RFC 8708 §4.2 | 620-659 |
//!
//! CNSA 2.0 (and CNSA 1.0 by mirror) permits every one of the 80 pairs.
//! CNSSP-15 Annex B states "all parameters appropriate to protect to TOP
//! SECRET" for LMS, recommending LMS-SHA-256/192, and so places no subset
//! restriction on the parameter sets — see
//! [`oxicrypt_module::is_allowed`].
//!
//! # Cached signing — `LmsSigningKey` (feature `alloc`)
//!
//! Each per-pair module additionally emits an `LmsSigningKey` wrapper
//! (behind the default-on `alloc` feature) that precomputes the full
//! Merkle node table once at construction (cost ≈ one keygen) and
//! reads authentication paths from it, taking per-signature tree cost
//! from O(2^H) to O(H). Signatures are byte-identical to the uncached
//! path. The node table holds only **public** Merkle data (derived
//! from the LM-OTS public keys), so it carries no zeroization
//! requirement; the wrapped `LmsPrivateKey` keeps its zeroize-on-Drop
//! semantics, and the stateful one-leaf-per-signature contract is
//! unchanged. The plain `keygen`/`sign`/`verify` surface stays
//! heap-free and is unaffected when `alloc` is disabled.
//!
//! # Self-tests
//!
//! [`KATS`] aggregates the power-up KATs for every instantiated pair.
//! Each pair runs one full keygen → sign → verify round trip plus
//! negative-verification assertions. Aggregate runtime is dominated by
//! the per-pair leaf-hashing cost (~0.5–1 s per pair at H = 10).
//!
//! # Sensitive security parameters (SSPs)
//!
//! | SSP | Location | Zeroized on Drop |
//! |---|---|---|
//! | Tree seed (N bytes) | `LmsPrivateKey::seed` | Yes |
//! | Tree identifier I (16 bytes) | `LmsPrivateKey::identifier` | Yes |
//!
//! # FIPS module gating
//!
//! Each pair's `sign` gates on its `Service::Lms<…>Sign`; `verify` gates
//! on `Service::Lms<…>Verify`. Both also gate on `require_operational`.
//!
//! LMS is the one family the CNSA profiles admit by a discriminant range
//! rather than by enumerated arms, because CNSSP-15 Annex B imposes no
//! subset on it. So the fail-safe default-deny that covers every other
//! family does **not** cover a new LMS pair: one added inside the reserved
//! block is automatically *permitted*, not denied. That is the intended
//! reading of the policy, and it is why
//! `oxicrypt_module`'s `lms_discriminant_block_is_contiguous_and_pure`
//! exists — it fails if anything but LMS ever lands in the block, which is
//! the case the range test cannot distinguish on its own.

// `no_std` by default. The optional `parallel` feature pulls in `rayon`,
// which requires `std`, so `std` enters ONLY under `parallel`; every
// default build remains provably `no_std`. `forbid(unsafe_code)` is
// unconditional in both configurations.
#![cfg_attr(not(feature = "parallel"), no_std)]
#![forbid(unsafe_code)]

#[cfg(feature = "alloc")]
extern crate alloc;

pub mod hash;
pub(crate) mod lms_impl;

// ── SHA-256 / M=32 family (RFC 8554 §A.1+§A.2) ──────────────────────
// 20 pairs: H ∈ {5, 10, 15, 20, 25} × W ∈ {1, 2, 4, 8}.

/// LMS_SHA256_M32_H10 / LMOTS_SHA256_N32_W1.
pub mod lms_sha256_m32_h10_w1;
/// LMS_SHA256_M32_H10 / LMOTS_SHA256_N32_W2.
pub mod lms_sha256_m32_h10_w2;
/// LMS_SHA256_M32_H10 / LMOTS_SHA256_N32_W4 — legacy baseline pair.
pub mod lms_sha256_m32_h10_w4;
/// LMS_SHA256_M32_H10 / LMOTS_SHA256_N32_W8.
pub mod lms_sha256_m32_h10_w8;
/// LMS_SHA256_M32_H15 / LMOTS_SHA256_N32_W1.
pub mod lms_sha256_m32_h15_w1;
/// LMS_SHA256_M32_H15 / LMOTS_SHA256_N32_W2.
pub mod lms_sha256_m32_h15_w2;
/// LMS_SHA256_M32_H15 / LMOTS_SHA256_N32_W4.
pub mod lms_sha256_m32_h15_w4;
/// LMS_SHA256_M32_H15 / LMOTS_SHA256_N32_W8.
pub mod lms_sha256_m32_h15_w8;
/// LMS_SHA256_M32_H20 / LMOTS_SHA256_N32_W1.
pub mod lms_sha256_m32_h20_w1;
/// LMS_SHA256_M32_H20 / LMOTS_SHA256_N32_W2.
pub mod lms_sha256_m32_h20_w2;
/// LMS_SHA256_M32_H20 / LMOTS_SHA256_N32_W4.
pub mod lms_sha256_m32_h20_w4;
/// LMS_SHA256_M32_H20 / LMOTS_SHA256_N32_W8.
pub mod lms_sha256_m32_h20_w8;
/// LMS_SHA256_M32_H25 / LMOTS_SHA256_N32_W1.
pub mod lms_sha256_m32_h25_w1;
/// LMS_SHA256_M32_H25 / LMOTS_SHA256_N32_W2.
pub mod lms_sha256_m32_h25_w2;
/// LMS_SHA256_M32_H25 / LMOTS_SHA256_N32_W4.
pub mod lms_sha256_m32_h25_w4;
/// LMS_SHA256_M32_H25 / LMOTS_SHA256_N32_W8.
pub mod lms_sha256_m32_h25_w8;
/// LMS_SHA256_M32_H5  / LMOTS_SHA256_N32_W1.
pub mod lms_sha256_m32_h5_w1;
/// LMS_SHA256_M32_H5  / LMOTS_SHA256_N32_W2.
pub mod lms_sha256_m32_h5_w2;
/// LMS_SHA256_M32_H5  / LMOTS_SHA256_N32_W4.
pub mod lms_sha256_m32_h5_w4;
/// LMS_SHA256_M32_H5  / LMOTS_SHA256_N32_W8.
pub mod lms_sha256_m32_h5_w8;

// ── SHA-256 / M=24 family (RFC 8708 §4.1) ───────────────────────────
// 20 pairs: H ∈ {5, 10, 15, 20, 25} × W ∈ {1, 2, 4, 8}.
/// LMS_SHA256_M24_H10 / LMOTS_SHA256_N24_W1.
pub mod lms_sha256_m24_h10_w1;
/// LMS_SHA256_M24_H10 / LMOTS_SHA256_N24_W2.
pub mod lms_sha256_m24_h10_w2;
/// LMS_SHA256_M24_H10 / LMOTS_SHA256_N24_W4.
pub mod lms_sha256_m24_h10_w4;
/// LMS_SHA256_M24_H10 / LMOTS_SHA256_N24_W8.
pub mod lms_sha256_m24_h10_w8;
/// LMS_SHA256_M24_H15 / LMOTS_SHA256_N24_W1.
pub mod lms_sha256_m24_h15_w1;
/// LMS_SHA256_M24_H15 / LMOTS_SHA256_N24_W2.
pub mod lms_sha256_m24_h15_w2;
/// LMS_SHA256_M24_H15 / LMOTS_SHA256_N24_W4.
pub mod lms_sha256_m24_h15_w4;
/// LMS_SHA256_M24_H15 / LMOTS_SHA256_N24_W8.
pub mod lms_sha256_m24_h15_w8;
/// LMS_SHA256_M24_H20 / LMOTS_SHA256_N24_W1.
pub mod lms_sha256_m24_h20_w1;
/// LMS_SHA256_M24_H20 / LMOTS_SHA256_N24_W2.
pub mod lms_sha256_m24_h20_w2;
/// LMS_SHA256_M24_H20 / LMOTS_SHA256_N24_W4.
pub mod lms_sha256_m24_h20_w4;
/// LMS_SHA256_M24_H20 / LMOTS_SHA256_N24_W8.
pub mod lms_sha256_m24_h20_w8;
/// LMS_SHA256_M24_H25 / LMOTS_SHA256_N24_W1.
pub mod lms_sha256_m24_h25_w1;
/// LMS_SHA256_M24_H25 / LMOTS_SHA256_N24_W2.
pub mod lms_sha256_m24_h25_w2;
/// LMS_SHA256_M24_H25 / LMOTS_SHA256_N24_W4.
pub mod lms_sha256_m24_h25_w4;
/// LMS_SHA256_M24_H25 / LMOTS_SHA256_N24_W8.
pub mod lms_sha256_m24_h25_w8;
/// LMS_SHA256_M24_H5 / LMOTS_SHA256_N24_W1.
pub mod lms_sha256_m24_h5_w1;
/// LMS_SHA256_M24_H5 / LMOTS_SHA256_N24_W2.
pub mod lms_sha256_m24_h5_w2;
/// LMS_SHA256_M24_H5 / LMOTS_SHA256_N24_W4.
pub mod lms_sha256_m24_h5_w4;
/// LMS_SHA256_M24_H5 / LMOTS_SHA256_N24_W8.
pub mod lms_sha256_m24_h5_w8;

// ── SHAKE-256 / M=32 family (RFC 8708 §3.1) ─────────────────────────
// 20 pairs: H ∈ {5, 10, 15, 20, 25} × W ∈ {1, 2, 4, 8}.
/// LMS_SHAKE_M32_H10 / LMOTS_SHAKE_N32_W1.
pub mod lms_shake_m32_h10_w1;
/// LMS_SHAKE_M32_H10 / LMOTS_SHAKE_N32_W2.
pub mod lms_shake_m32_h10_w2;
/// LMS_SHAKE_M32_H10 / LMOTS_SHAKE_N32_W4.
pub mod lms_shake_m32_h10_w4;
/// LMS_SHAKE_M32_H10 / LMOTS_SHAKE_N32_W8.
pub mod lms_shake_m32_h10_w8;
/// LMS_SHAKE_M32_H15 / LMOTS_SHAKE_N32_W1.
pub mod lms_shake_m32_h15_w1;
/// LMS_SHAKE_M32_H15 / LMOTS_SHAKE_N32_W2.
pub mod lms_shake_m32_h15_w2;
/// LMS_SHAKE_M32_H15 / LMOTS_SHAKE_N32_W4.
pub mod lms_shake_m32_h15_w4;
/// LMS_SHAKE_M32_H15 / LMOTS_SHAKE_N32_W8.
pub mod lms_shake_m32_h15_w8;
/// LMS_SHAKE_M32_H20 / LMOTS_SHAKE_N32_W1.
pub mod lms_shake_m32_h20_w1;
/// LMS_SHAKE_M32_H20 / LMOTS_SHAKE_N32_W2.
pub mod lms_shake_m32_h20_w2;
/// LMS_SHAKE_M32_H20 / LMOTS_SHAKE_N32_W4.
pub mod lms_shake_m32_h20_w4;
/// LMS_SHAKE_M32_H20 / LMOTS_SHAKE_N32_W8.
pub mod lms_shake_m32_h20_w8;
/// LMS_SHAKE_M32_H25 / LMOTS_SHAKE_N32_W1.
pub mod lms_shake_m32_h25_w1;
/// LMS_SHAKE_M32_H25 / LMOTS_SHAKE_N32_W2.
pub mod lms_shake_m32_h25_w2;
/// LMS_SHAKE_M32_H25 / LMOTS_SHAKE_N32_W4.
pub mod lms_shake_m32_h25_w4;
/// LMS_SHAKE_M32_H25 / LMOTS_SHAKE_N32_W8.
pub mod lms_shake_m32_h25_w8;
/// LMS_SHAKE_M32_H5 / LMOTS_SHAKE_N32_W1.
pub mod lms_shake_m32_h5_w1;
/// LMS_SHAKE_M32_H5 / LMOTS_SHAKE_N32_W2.
pub mod lms_shake_m32_h5_w2;
/// LMS_SHAKE_M32_H5 / LMOTS_SHAKE_N32_W4.
pub mod lms_shake_m32_h5_w4;
/// LMS_SHAKE_M32_H5 / LMOTS_SHAKE_N32_W8.
pub mod lms_shake_m32_h5_w8;

// ── SHAKE-256 / M=24 family (RFC 8708 §4.2) ─────────────────────────
// 20 pairs: H ∈ {5, 10, 15, 20, 25} × W ∈ {1, 2, 4, 8}.
/// LMS_SHAKE_M24_H10 / LMOTS_SHAKE_N24_W1.
pub mod lms_shake_m24_h10_w1;
/// LMS_SHAKE_M24_H10 / LMOTS_SHAKE_N24_W2.
pub mod lms_shake_m24_h10_w2;
/// LMS_SHAKE_M24_H10 / LMOTS_SHAKE_N24_W4.
pub mod lms_shake_m24_h10_w4;
/// LMS_SHAKE_M24_H10 / LMOTS_SHAKE_N24_W8.
pub mod lms_shake_m24_h10_w8;
/// LMS_SHAKE_M24_H15 / LMOTS_SHAKE_N24_W1.
pub mod lms_shake_m24_h15_w1;
/// LMS_SHAKE_M24_H15 / LMOTS_SHAKE_N24_W2.
pub mod lms_shake_m24_h15_w2;
/// LMS_SHAKE_M24_H15 / LMOTS_SHAKE_N24_W4.
pub mod lms_shake_m24_h15_w4;
/// LMS_SHAKE_M24_H15 / LMOTS_SHAKE_N24_W8.
pub mod lms_shake_m24_h15_w8;
/// LMS_SHAKE_M24_H20 / LMOTS_SHAKE_N24_W1.
pub mod lms_shake_m24_h20_w1;
/// LMS_SHAKE_M24_H20 / LMOTS_SHAKE_N24_W2.
pub mod lms_shake_m24_h20_w2;
/// LMS_SHAKE_M24_H20 / LMOTS_SHAKE_N24_W4.
pub mod lms_shake_m24_h20_w4;
/// LMS_SHAKE_M24_H20 / LMOTS_SHAKE_N24_W8.
pub mod lms_shake_m24_h20_w8;
/// LMS_SHAKE_M24_H25 / LMOTS_SHAKE_N24_W1.
pub mod lms_shake_m24_h25_w1;
/// LMS_SHAKE_M24_H25 / LMOTS_SHAKE_N24_W2.
pub mod lms_shake_m24_h25_w2;
/// LMS_SHAKE_M24_H25 / LMOTS_SHAKE_N24_W4.
pub mod lms_shake_m24_h25_w4;
/// LMS_SHAKE_M24_H25 / LMOTS_SHAKE_N24_W8.
pub mod lms_shake_m24_h25_w8;
/// LMS_SHAKE_M24_H5 / LMOTS_SHAKE_N24_W1.
pub mod lms_shake_m24_h5_w1;
/// LMS_SHAKE_M24_H5 / LMOTS_SHAKE_N24_W2.
pub mod lms_shake_m24_h5_w2;
/// LMS_SHAKE_M24_H5 / LMOTS_SHAKE_N24_W4.
pub mod lms_shake_m24_h5_w4;
/// LMS_SHAKE_M24_H5 / LMOTS_SHAKE_N24_W8.
pub mod lms_shake_m24_h5_w8;

// ── Backwards-compat re-exports ─────────────────────────────────────
//
// Until the per-pair callers in `oxicrypt-ffi` / `acvp-harness` /
// `tests/nist_kat.rs` move to addressing variant modules explicitly,
// the baseline pair's surface stays reachable at the crate root. New
// callers should reach for the per-pair module they need by name
// (`oxicrypt_lms::lms_sha256_m32_h10_w4`, …).
pub use lms_sha256_m32_h10_w4::{
    KATS, LmsPrivateKey, MAX_SIGNATURES, PRIVATE_KEY_LEN, PUBLIC_KEY_LEN, SIGNATURE_LEN, keygen,
    keygen_from_parts, keygen_internal, sign, sign_internal, verify, verify_internal,
};
