//! LMS_SHA256_M32_H25 / LMOTS_SHA256_N32_W1 instantiation.
//!
//! Parameters: hash = SHA-256, N = 32, H = 25 (33554432
//! signatures), W = 1 (Winternitz). Derived (RFC 8554 §4.1):
//! U = 256, V = 9, P = 265, LS = 7.
//!
//! Generated by `lms_impl!`. External KAT grounding:
//! one passing sigVer test case vendored from
//! `usnistgov/ACVP-Server @ 112690e8` (vsId-tg derived per pair), run
//! by `tests/nist_kat_all_pairs.rs`.

use oxicrypt_module::Service;

crate::lms_impl::lms_impl! {
    hasher = crate::hash::Sha256N32;
    n = 32;
    h = 25;
    w = 1;
    u = 256;
    v = 9;
    p = 265;
    ls = 7;
    lms_type = 0x0000_0009;
    lmots_type = 0x0000_0001;
    svc_sign = Service::LmsSha256M32H25W1Sign;
    svc_verify = Service::LmsSha256M32H25W1Verify;
    kat_xi = [
        0x4c, 0x4d, 0x53, 0x2d, 0x4b, 0x41, 0x54, 0x2d, // "LMS-KAT-"
        0x53, 0x50, 0x38, 0x30, 0x30, 0x2d, 0x32, 0x30, // "SP800-20"
        0x38, 0x2d, 0x6f, 0x78, 0x69, 0x63, 0x72, 0x79, // "8-oxicry"
        0x70, 0x74, 0x2d, 0x76, 0x30, 0x2e, 0x30, 0x2e, // "pt-v0.0."
    ];
    kat_msg = b"LMS self-test message for SP 800-208 / FIPS 140-3 compliance";
    kat_name = "LMS KAT (LMS_SHA256_M32_H25 / LMOTS_SHA256_N32_W1 keygen+sign+verify round-trip, SP 800-208)";
}
