//! LMS_SHA256_M32_H25 / LMOTS_SHA256_N32_W8 instantiation.
//!
//! Parameters: hash = SHA-256, N = 32, H = 25 (33554432
//! signatures), W = 8 (Winternitz). Derived (RFC 8554 §4.1):
//! U = 32, V = 2, P = 34, LS = 0.
//!
//! Generated by [`lms_impl!`](crate::lms_impl). External KAT grounding:
//! one passing sigVer test case vendored from
//! `usnistgov/ACVP-Server @ 112690e8` (vsId-tg derived per pair), run
//! by `tests/nist_kat_all_pairs.rs`.

use oxicrypt_module::Service;

crate::lms_impl::lms_impl! {
    hasher = crate::hash::Sha256N32;
    n = 32;
    h = 25;
    w = 8;
    u = 32;
    v = 2;
    p = 34;
    ls = 0;
    lms_type = 0x0000_0009;
    lmots_type = 0x0000_0004;
    svc_sign = Service::LmsSha256M32H25W8Sign;
    svc_verify = Service::LmsSha256M32H25W8Verify;
    kat_xi = [
        0x4c, 0x4d, 0x53, 0x2d, 0x4b, 0x41, 0x54, 0x2d, // "LMS-KAT-"
        0x53, 0x50, 0x38, 0x30, 0x30, 0x2d, 0x32, 0x30, // "SP800-20"
        0x38, 0x2d, 0x6f, 0x78, 0x69, 0x63, 0x72, 0x79, // "8-oxicry"
        0x70, 0x74, 0x2d, 0x76, 0x30, 0x2e, 0x30, 0x2e, // "pt-v0.0."
    ];
    kat_msg = b"LMS self-test message for SP 800-208 / FIPS 140-3 compliance";
    kat_name = "LMS KAT (LMS_SHA256_M32_H25 / LMOTS_SHA256_N32_W8 keygen+sign+verify round-trip, SP 800-208)";
}

// ── Parallel keyGen root determinism oracle (H = 25, pre-submission) ──
//
// For #129: the tall-tree counterpart to the H=15 oracle, at the largest
// CNSA tree (2^25 leaves, W = 8 — the costliest keyGen). Asserts the
// parallel `keygen_from_parts` root is byte-identical to the serial
// `keygen_internal` root. Ignored by default: it allocates ~2 GiB and
// computes 2^25 W=8 leaves twice (serial + parallel), which runs for
// minutes. Run explicitly as the pre-ACVTS-submission gate:
//   cargo test -p oxicrypt-lms --features parallel --release -- \
//     --ignored parallel_keygen_from_parts_root_matches_serial_h25
#[cfg(all(test, feature = "parallel"))]
#[allow(clippy::unwrap_used, clippy::indexing_slicing)]
mod parallel_keygen_oracle {
    use super::*;

    #[test]
    #[ignore = "H25: ~2 GiB and minutes — pre-ACVTS-submission oracle; run with --ignored"]
    fn parallel_keygen_from_parts_root_matches_serial_h25() {
        let (sk, pk_serial) = keygen_internal(&KAT_XI);
        let (_sk, pk_parallel) = keygen_from_parts(&sk.seed, &sk.identifier);
        assert_eq!(
            pk_serial, pk_parallel,
            "parallel keygen_from_parts root diverged from serial keygen at H=25"
        );
    }
}
