//! LMS_SHA256_M32_H15 / LMOTS_SHA256_N32_W4 instantiation.
//!
//! Parameters: hash = SHA-256, N = 32, H = 15 (32768
//! signatures), W = 4 (Winternitz). Derived (RFC 8554 §4.1):
//! U = 64, V = 3, P = 67, LS = 4.
//!
//! Generated by `lms_impl!`. External KAT grounding:
//! one passing sigVer test case vendored from
//! `usnistgov/ACVP-Server @ 112690e8` (vsId-tg derived per pair), run
//! by `tests/nist_kat_all_pairs.rs`.

use oxicrypt_module::Service;

crate::lms_impl::lms_impl! {
    hasher = crate::hash::Sha256N32;
    n = 32;
    h = 15;
    w = 4;
    u = 64;
    v = 3;
    p = 67;
    ls = 4;
    lms_type = 0x0000_0007;
    lmots_type = 0x0000_0003;
    svc_sign = Service::LmsSha256M32H15W4Sign;
    svc_verify = Service::LmsSha256M32H15W4Verify;
    kat_xi = [
        0x4c, 0x4d, 0x53, 0x2d, 0x4b, 0x41, 0x54, 0x2d, // "LMS-KAT-"
        0x53, 0x50, 0x38, 0x30, 0x30, 0x2d, 0x32, 0x30, // "SP800-20"
        0x38, 0x2d, 0x6f, 0x78, 0x69, 0x63, 0x72, 0x79, // "8-oxicry"
        0x70, 0x74, 0x2d, 0x76, 0x30, 0x2e, 0x30, 0x2e, // "pt-v0.0."
    ];
    kat_msg = b"LMS self-test message for SP 800-208 / FIPS 140-3 compliance";
    kat_name = "LMS KAT (LMS_SHA256_M32_H15 / LMOTS_SHA256_N32_W4 keygen+sign+verify round-trip, SP 800-208)";
}

// ── Parallel keyGen root determinism oracle (H = 15) ────────────────
//
// For #129: under the `parallel` feature, `keygen_from_parts` (the ACVP
// keyGen entry) derives the Merkle root via the parallel `build_node_table`
// leaf sweep instead of the serial recursive `compute_root`. This asserts
// that root is byte-identical to the serial `keygen_internal` (which uses
// `compute_root`) for the same seed — the R75 property an ACVTS keyGen
// submission depends on, at a tall tree the H ≤ 10 oracles never reached.
// Only meaningful under `parallel` (the default build's `keygen_from_parts`
// is already the serial path), so feature-gated. It runs a serial
// (`keygen_internal`) and a parallel (`keygen_from_parts`) full-tree keyGen at
// H = 15 (2^15 leaves): a few seconds in `--release`, but ~3-4 min in a debug
// build (dominated by the single-threaded serial reference half). Feature-gated,
// so neither the default gate nor the pre-push hook runs it — only an explicit
// `--features parallel` test invocation does.
#[cfg(all(test, feature = "parallel"))]
#[allow(clippy::unwrap_used, clippy::indexing_slicing)]
mod parallel_keygen_oracle {
    use super::*;

    #[test]
    fn parallel_keygen_from_parts_root_matches_serial_h15() {
        let (sk, pk_serial) = keygen_internal(&KAT_XI);
        let (_sk, pk_parallel) = keygen_from_parts(&sk.seed, &sk.identifier);
        assert_eq!(
            pk_serial, pk_parallel,
            "parallel keygen_from_parts root diverged from serial keygen at H=15"
        );
    }
}
