//! LMS_SHAKE_M24_H15 / LMOTS_SHAKE_N24_W1 instantiation.
//!
//! Parameters: hash = SHAKE-256, N = 24, H = 15 (32768
//! signatures), W = 1 (Winternitz). Derived (RFC 8554 §4.1):
//! U = 192, V = 8, P = 200, LS = 8.
//!
//! Generated by `lms_impl!`. External KAT grounding:
//! one passing sigVer test case vendored from
//! `usnistgov/ACVP-Server @ 112690e8` (vsId-tg derived per pair), run
//! by `tests/nist_kat_all_pairs.rs`.

use oxicrypt_module::Service;

crate::lms_impl::lms_impl! {
    hasher = crate::hash::Shake256N24;
    n = 24;
    h = 15;
    w = 1;
    u = 192;
    v = 8;
    p = 200;
    ls = 8;
    lms_type = 0x0000_0016;
    lmots_type = 0x0000_000d;
    svc_sign = Service::LmsShakeM24H15W1Sign;
    svc_verify = Service::LmsShakeM24H15W1Verify;
    kat_xi = [
        0x4c, 0x4d, 0x53, 0x2d, 0x4b, 0x41, 0x54, 0x2d, // "LMS-KAT-"
        0x53, 0x50, 0x38, 0x30, 0x30, 0x2d, 0x32, 0x30, // "SP800-20"
        0x38, 0x2d, 0x6f, 0x78, 0x69, 0x63, 0x72, 0x79, // "8-oxicry"
        0x70, 0x74, 0x2d, 0x76, 0x30, 0x2e, 0x30, 0x2e, // "pt-v0.0."
    ];
    kat_msg = b"LMS self-test message for SP 800-208 / FIPS 140-3 compliance";
    kat_name = "LMS KAT (LMS_SHAKE_M24_H15 / LMOTS_SHAKE_N24_W1 keygen+sign+verify round-trip, SP 800-208)";
}
