//! LMS_SHAKE_M24_H20 / LMOTS_SHAKE_N24_W4 instantiation.
//!
//! Parameters: hash = SHAKE-256, N = 24, H = 20 (1048576
//! signatures), W = 4 (Winternitz). Derived (RFC 8554 §4.1):
//! U = 48, V = 3, P = 51, LS = 4.
//!
//! Generated by `lms_impl!`. External KAT grounding:
//! one passing sigVer test case vendored from
//! `usnistgov/ACVP-Server @ 112690e8` (vsId-tg derived per pair), run
//! by `tests/nist_kat_all_pairs.rs`.

use oxicrypt_module::Service;

crate::lms_impl::lms_impl! {
    hasher = crate::hash::Shake256N24;
    n = 24;
    h = 20;
    w = 4;
    u = 48;
    v = 3;
    p = 51;
    ls = 4;
    lms_type = 0x0000_0017;
    lmots_type = 0x0000_000f;
    svc_sign = Service::LmsShakeM24H20W4Sign;
    svc_verify = Service::LmsShakeM24H20W4Verify;
    kat_xi = [
        0x4c, 0x4d, 0x53, 0x2d, 0x4b, 0x41, 0x54, 0x2d, // "LMS-KAT-"
        0x53, 0x50, 0x38, 0x30, 0x30, 0x2d, 0x32, 0x30, // "SP800-20"
        0x38, 0x2d, 0x6f, 0x78, 0x69, 0x63, 0x72, 0x79, // "8-oxicry"
        0x70, 0x74, 0x2d, 0x76, 0x30, 0x2e, 0x30, 0x2e, // "pt-v0.0."
    ];
    kat_msg = b"LMS self-test message for SP 800-208 / FIPS 140-3 compliance";
    kat_name = "LMS KAT (LMS_SHAKE_M24_H20 / LMOTS_SHAKE_N24_W4 keygen+sign+verify round-trip, SP 800-208)";
}
