//! LMS_SHA256_M32_H10 / LMOTS_SHA256_N32_W4 instantiation.
//!
//! Parameters: hash = SHA-256, N = 32, H = 10 (1024 signatures),
//! W = 4 (Winternitz), per RFC 8554 §A.1+§A.2.
//!
//! Derived (RFC 8554 §4.1): U = 64, V = 3, P = 67, LS = 4.
//!
//! Generated by [`lms_impl!`](crate::lms_impl). This file is the
//! baseline pair that was hand-written in the v0.0.x crate before the
//! macro foundation landed; the macro reproduces it byte-for-byte.
//!
//! # Approved services
//!
//! | Service | Standard | Service ID |
//! |---|---|---|
//! | LMS sign | SP 800-208 (RFC 8554) | `Service::LmsSha256M32H10W4Sign` (512) |
//! | LMS verify | SP 800-208 (RFC 8554) | `Service::LmsSha256M32H10W4Verify` (513) |
//!
//! This pair is one of the 8 CNSA 2.0 permitted (LMS, LM-OTS)
//! combinations per CNSSP-15.
//!
//! # Sensitive security parameters (SSPs)
//!
//! | SSP | Location | Zeroized on Drop |
//! |---|---|---|
//! | Tree seed (32 bytes) | `LmsPrivateKey::seed` | Yes |
//! | Tree identifier I (16 bytes) | `LmsPrivateKey::identifier` | Yes |

use oxicrypt_module::Service;

crate::lms_impl::lms_impl! {
    hasher = crate::hash::Sha256N32;
    n = 32;
    h = 10;
    w = 4;
    u = 64;
    v = 3;
    p = 67;
    ls = 4;
    lms_type = 0x0000_0006;
    lmots_type = 0x0000_0003;
    svc_sign = Service::LmsSha256M32H10W4Sign;
    svc_verify = Service::LmsSha256M32H10W4Verify;
    kat_xi = [
        0x4c, 0x4d, 0x53, 0x2d, 0x4b, 0x41, 0x54, 0x2d, // "LMS-KAT-"
        0x53, 0x50, 0x38, 0x30, 0x30, 0x2d, 0x32, 0x30, // "SP800-20"
        0x38, 0x2d, 0x6f, 0x78, 0x69, 0x63, 0x72, 0x79, // "8-oxicry"
        0x70, 0x74, 0x2d, 0x76, 0x30, 0x2e, 0x30, 0x2e, // "pt-v0.0."
    ];
    kat_msg = b"LMS self-test message for SP 800-208 / FIPS 140-3 compliance";
    kat_name = "LMS KAT (LMS_SHA256_M32_H10 keygen+sign+verify round-trip, SP 800-208)";
}

// ── Unit tests ──────────────────────────────────────────────────────
//
// These tests live in the baseline pair file rather than the macro
// body so that pairs with `H ≥ 15` — whose `keygen` walks 2^H leaves
// and would take minutes per case — are not forced into the test
// suite. Each non-baseline pair file may emit its own constant-check
// tests (mirroring the slh-dsa `variant_tests` pattern) without the
// full round-trip cost.

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic, clippy::indexing_slicing)]
mod tests {
    use super::*;
    use oxicrypt_module::{KatEntry, initialize_with_tests};

    fn ensure_initialized() {
        let _ = initialize_with_tests(&[KatEntry {
            name: "lms-unit-test-bootstrap",
            run: self_test,
        }]);
    }

    #[test]
    fn self_test_passes() {
        self_test().unwrap();
    }

    #[test]
    fn keygen_produces_valid_public_key() {
        let xi = [0x42u8; 32];
        let (_sk, pk) = keygen_internal(&xi);
        let lms_type = u32::from_be_bytes([pk[0], pk[1], pk[2], pk[3]]);
        assert_eq!(lms_type, LMS_TYPE);
        let ots_type = u32::from_be_bytes([pk[4], pk[5], pk[6], pk[7]]);
        assert_eq!(ots_type, LMOTS_TYPE);
    }

    #[test]
    fn sign_advances_leaf_index() {
        let (mut sk, _pk) = keygen_internal(&KAT_XI);
        assert_eq!(sk.leaf_index(), 0);
        let _ = sign_internal(&mut sk, b"msg1");
        assert_eq!(sk.leaf_index(), 1);
        let _ = sign_internal(&mut sk, b"msg2");
        assert_eq!(sk.leaf_index(), 2);
    }

    #[test]
    fn different_messages_produce_different_signatures() {
        let (mut sk, _pk) = keygen_internal(&KAT_XI);
        let sig1 = sign_internal(&mut sk, b"message A").unwrap();
        let (mut sk2, _) = keygen_internal(&KAT_XI);
        let sig2 = sign_internal(&mut sk2, b"message B").unwrap();
        assert_ne!(sig1, sig2);
    }

    #[test]
    fn verify_fails_on_wrong_public_key() {
        let (mut sk, _pk) = keygen_internal(&KAT_XI);
        let sig = sign_internal(&mut sk, KAT_MSG).unwrap();
        let (_sk2, pk2) = keygen_internal(&[0xFFu8; 32]);
        assert!(!verify_internal(&pk2, KAT_MSG, &sig));
    }

    #[test]
    fn private_key_round_trips_through_bytes() {
        let (sk, _pk) = keygen_internal(&KAT_XI);
        let bytes = sk.to_bytes();
        let sk2 = LmsPrivateKey::from_bytes(&bytes).unwrap();
        assert_eq!(sk.to_bytes(), sk2.to_bytes());
    }

    #[test]
    fn gated_api_works_after_init() {
        ensure_initialized();
        let (mut sk, pk) = keygen(&[0x99u8; 32]).unwrap();
        let sig = sign(&mut sk, b"gated test").unwrap();
        verify(&pk, b"gated test", &sig).unwrap();
    }
}
