//! SLH-DSA-SHA2-256s instantiation (FIPS 205 §11 Table 2).
//!
//! Parameters: n=32, h=64, d=8, h'=8, a=14, k=22, w=16.
//! Sizes: PK_LEN=64, SK_LEN=128, SIG_LEN=29 792.
//!
//! Generated by the `slh_dsa_impl!` macro.
//!
//! # Approved services
//!
//! | Service | Standard | Profile |
//! |---------|----------|---------|
//! | SLH-DSA keygen | FIPS 205 | Unrestricted, CNSA 2.0 (mandate) |
//! | SLH-DSA sign   | FIPS 205 | Unrestricted, CNSA 2.0 (mandate) |
//! | SLH-DSA verify | FIPS 205 | Unrestricted, CNSA 2.0 (mandate) |
//!
//! SHA2-256s is the CNSA 2.0 stateless-hash-based signature mandate
//! (CNSSP 15) and is permitted under all profiles. The remaining 11
//! SLH-DSA parameter sets (when added) will be `Unrestricted`-only.
//!
//! # External vs internal API
//!
//! [`keygen`], [`sign`], [`verify`] implement the FIPS 205 §9.2 / §9.3
//! external API with `ctx` framing (`M' = 0x00 || |ctx| || ctx || M`).
//! [`keygen_internal`], [`sign_internal`], [`verify_internal`] expose
//! Algorithms 17, 19, 20 directly for CAVP / ACVP harnesses.

#![allow(
    clippy::arithmetic_side_effects,
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::indexing_slicing,
    clippy::integer_division,
    clippy::large_stack_arrays,
    clippy::manual_div_ceil,
    clippy::needless_range_loop,
    clippy::similar_names,
    clippy::too_many_lines,
    clippy::unnecessary_cast,
    clippy::unwrap_used,
    clippy::many_single_char_names,
    dead_code
)]

crate::slh_dsa_impl::slh_dsa_impl! {
    hash_family = sha2;
    n = 32;
    h = 64;
    d = 8;
    a = 14;
    k = 22;
    lg_w = 4;
    svc_keygen = Service::SlhDsaSha2256sKeygen;
    svc_sign = Service::SlhDsaSha2256sSign;
    svc_verify = Service::SlhDsaSha2256sVerify;
    kat_seed_offset = 0u8;
    kat_msg = b"SLH-DSA-SHA2-256s self-test message (FIPS 205)";
    kat_name = "SLH-DSA-SHA2-256s KAT (keygen + sign + verify round-trip, FIPS 205)";
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic)]
mod variant_tests {
    use super::*;

    #[test]
    fn paramset_dispatch_emits_sha512_long_hash() {
        // FIPS 205 §10.1 Table 5: at n=24/32, H/T/PRF_msg/H_msg use
        // SHA-512 truncated. `__sha2_long_setup!($n)` must hit the
        // catch-all arm. See CMVP gem in security-policy.md for the
        // macro_rules :literal-hygiene incident that motivated this assert.
        assert_eq!(LONG_PAD, 96, "long-hash pad must be 128-N (SHA-512)");
        assert_eq!(LONG_BLOCK, 128, "long-hash block must be 128 (SHA-512)");
        assert_eq!(LONG_OUT, 64, "long-hash out must be 64 (SHA-512)");
    }

    #[test]
    fn key_sizes_match_spec() {
        assert_eq!(PK_LEN, 64);
        assert_eq!(SK_LEN, 128);
        assert_eq!(SIG_LEN, 29_792);
    }

    #[test]
    fn parameter_constants_match_spec() {
        assert_eq!(N, 32);
        assert_eq!(H, 64);
        assert_eq!(D, 8);
        assert_eq!(H_PRIME, 8);
        assert_eq!(A, 14);
        assert_eq!(K, 22);
        assert_eq!(LG_W, 4);
        assert_eq!(W, 16);
        assert_eq!(LEN1, 64);
        assert_eq!(LEN2, 3);
        assert_eq!(LEN, 67);
    }

    /// Best-effort wall-clock for one SHA2-256s keygen — the slowest
    /// (tallest-tree) SHA-2 parameter set, where the WOTS+ chain sweep
    /// dominates keygen cost. Gated on the `parallel` feature because it
    /// needs `std::time` (the default build is `#![no_std]`); compare
    /// thread counts on the same parallel build to isolate the speedup:
    ///
    /// ```text
    /// # baseline (one worker) vs 4 workers, release:
    /// RAYON_NUM_THREADS=1 cargo test -p oxicrypt-slh-dsa --release --features parallel \
    ///   slh_dsa_sha2_256s::variant_tests::keygen_timing -- --ignored --nocapture
    /// RAYON_NUM_THREADS=4 cargo test -p oxicrypt-slh-dsa --release --features parallel \
    ///   slh_dsa_sha2_256s::variant_tests::keygen_timing -- --ignored --nocapture
    /// ```
    #[cfg(feature = "parallel")]
    #[test]
    #[ignore = "timing benchmark, run explicitly with --ignored --nocapture"]
    #[allow(clippy::print_stdout)] // intentional: human-read timing output
    fn keygen_timing() {
        let mut xi = [0u8; 3 * N];
        for (i, b) in xi.iter_mut().enumerate() {
            *b = ((i & 0xFF) as u8).wrapping_mul(37).wrapping_add(7);
        }
        let start = std::time::Instant::now();
        let (pk, _sk) = keygen_internal(&xi);
        let elapsed = start.elapsed();
        // Touch the output so the keygen is not optimized away.
        assert_eq!(pk.len(), PK_LEN);
        let threads = std::env::var("RAYON_NUM_THREADS").unwrap_or_else(|_| "default".into());
        println!("SHA2-256s keygen_internal (RAYON_NUM_THREADS={threads}): {elapsed:?}");
    }
}
