//! SLH-DSA-SHAKE-256f instantiation (FIPS 205 §11 Table 2).
//!
//! Parameters: n=32, h=68, d=17, h'=4, a=9, k=35, w=16.
//! Sizes: PK_LEN=64, SK_LEN=128, SIG_LEN=49 856.
//!
//! Generated by the `slh_dsa_impl!` macro with `hash_family = shake`.
//!
//! # Approved services
//!
//! | Service | Standard | Profile |
//! |---------|----------|---------|
//! | SLH-DSA keygen | FIPS 205 | Unrestricted |
//! | SLH-DSA sign   | FIPS 205 | Unrestricted |
//! | SLH-DSA verify | FIPS 205 | Unrestricted |
//!
//! SHAKE-256f is permitted in the FIPS 140-3 Unrestricted profile and is
//! not on the CNSA 2.0 mandate list. CNSA 2.0 gating is denied at the
//! Service-enum layer in Batch 4.
//!
//! # External vs internal API
//!
//! [`keygen`], [`sign`], [`verify`] implement the FIPS 205 §9.2 / §9.3
//! external API with `ctx` framing (`M' = 0x00 || |ctx| || ctx || M`).
//! [`keygen_internal`], [`sign_internal`], [`verify_internal`] expose
//! Algorithms 17, 19, 20 directly for CAVP / ACVP harnesses.

#![allow(
    clippy::arithmetic_side_effects,
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::indexing_slicing,
    clippy::integer_division,
    clippy::large_stack_arrays,
    clippy::manual_div_ceil,
    clippy::needless_range_loop,
    clippy::similar_names,
    clippy::too_many_lines,
    clippy::unnecessary_cast,
    clippy::unwrap_used,
    clippy::many_single_char_names,
    dead_code
)]

crate::slh_dsa_impl::slh_dsa_impl! {
    hash_family = shake;
    n = 32;
    h = 68;
    d = 17;
    a = 9;
    k = 35;
    lg_w = 4;
    svc_keygen = Service::SlhDsaShake256fKeygen;
    svc_sign = Service::SlhDsaShake256fSign;
    svc_verify = Service::SlhDsaShake256fVerify;
    kat_seed_offset = 11u8;
    kat_msg = b"SLH-DSA-SHAKE-256f self-test message (FIPS 205)";
    kat_name = "SLH-DSA-SHAKE-256f KAT (keygen + sign + verify round-trip, FIPS 205)";
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic)]
mod variant_tests {
    use super::*;

    #[test]
    fn key_sizes_match_spec() {
        assert_eq!(PK_LEN, 64);
        assert_eq!(SK_LEN, 128);
        assert_eq!(SIG_LEN, 49_856);
    }

    #[test]
    fn parameter_constants_match_spec() {
        assert_eq!(N, 32);
        assert_eq!(H, 68);
        assert_eq!(D, 17);
        assert_eq!(H_PRIME, 4);
        assert_eq!(A, 9);
        assert_eq!(K, 35);
        assert_eq!(LG_W, 4);
        assert_eq!(W, 16);
        assert_eq!(LEN1, 64);
        assert_eq!(LEN2, 3);
        assert_eq!(LEN, 67);
    }
}
