//! SLH-DSA-SHA2-128s instantiation (FIPS 205 §11 Table 2).
//!
//! Parameters: n=16, h=63, d=7, h'=9, a=12, k=14, w=16.
//! Sizes: PK_LEN=32, SK_LEN=64, SIG_LEN=7 856.
//!
//! Generated by the `slh_dsa_impl!` macro.
//!
//! # Approved services
//!
//! | Service | Standard | Profile |
//! |---------|----------|---------|
//! | SLH-DSA keygen | FIPS 205 | Unrestricted |
//! | SLH-DSA sign   | FIPS 205 | Unrestricted |
//! | SLH-DSA verify | FIPS 205 | Unrestricted |
//!
//! SHA2-128s is permitted in the FIPS 140-3 Unrestricted profile. It is
//! not on the CNSA 2.0 mandate list (CNSSP 15 requires SHA2-256s for
//! stateless-hash-based signatures); CNSA 2.0 gating is denied at the
//! Service-enum layer in Batch 4.
//!
//! # External vs internal API
//!
//! [`keygen`], [`sign`], [`verify`] implement the FIPS 205 §9.2 / §9.3
//! external API with `ctx` framing (`M' = 0x00 || |ctx| || ctx || M`).
//! [`keygen_internal`], [`sign_internal`], [`verify_internal`] expose
//! Algorithms 17, 19, 20 directly for CAVP / ACVP harnesses.

#![allow(
    clippy::arithmetic_side_effects,
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::indexing_slicing,
    clippy::integer_division,
    clippy::large_stack_arrays,
    clippy::manual_div_ceil,
    clippy::needless_range_loop,
    clippy::similar_names,
    clippy::too_many_lines,
    clippy::unnecessary_cast,
    clippy::unwrap_used,
    clippy::many_single_char_names,
    dead_code
)]

crate::slh_dsa_impl::slh_dsa_impl! {
    hash_family = sha2;
    n = 16;
    h = 63;
    d = 7;
    a = 12;
    k = 14;
    lg_w = 4;
    svc_keygen = Service::SlhDsaSha2128sKeygen;
    svc_sign = Service::SlhDsaSha2128sSign;
    svc_verify = Service::SlhDsaSha2128sVerify;
    kat_seed_offset = 1u8;
    kat_msg = b"SLH-DSA-SHA2-128s self-test message (FIPS 205)";
    kat_name = "SLH-DSA-SHA2-128s KAT (keygen + sign + verify round-trip, FIPS 205)";
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic)]
mod variant_tests {
    use super::*;

    #[test]
    fn paramset_dispatch_emits_sha256_long_hash() {
        // Defends `feedback_macro_rules_literal_hygiene` (CMVP gem).
        // At n=16, FIPS 205 §10.1 Table 5 requires SHA-256 (not SHA-512)
        // for H, T, PRF_msg, H_msg. `__sha2_long_setup!(16)` emits
        // `LONG_PAD = 64 - N = 48` and `LONG_BLOCK = 64`. A prior bug
        // where the outer macro captured `$n` as `:literal` caused
        // every SHA-2 variant to fall through to the SHA-512 catch-all
        // arm (LONG_PAD = 128 - N), silently swapping the hash for
        // SLH-DSA-SHA2-128s and -128f. The fix is `$n:tt` capture so
        // the literal `(16)` arm matches when re-substituted. This
        // assertion is the fast regression signal — fires at run-time
        // BEFORE the (slower) NIST KAT path.
        assert_eq!(LONG_PAD, 48, "n=16 long-hash pad must be 48 (SHA-256)");
        assert_eq!(LONG_BLOCK, 64, "n=16 long-hash block must be 64 (SHA-256)");
        assert_eq!(LONG_OUT, 32, "n=16 long-hash out must be 32 (SHA-256)");
        assert_eq!(PAD256, 48, "n=16 SHA-256 short-hash pad must be 48");
    }

    #[test]
    fn key_sizes_match_spec() {
        assert_eq!(PK_LEN, 32);
        assert_eq!(SK_LEN, 64);
        assert_eq!(SIG_LEN, 7_856);
    }

    #[test]
    fn parameter_constants_match_spec() {
        assert_eq!(N, 16);
        assert_eq!(H, 63);
        assert_eq!(D, 7);
        assert_eq!(H_PRIME, 9);
        assert_eq!(A, 12);
        assert_eq!(K, 14);
        assert_eq!(LG_W, 4);
        assert_eq!(W, 16);
        assert_eq!(LEN1, 32);
        assert_eq!(LEN2, 3);
        assert_eq!(LEN, 35);
    }
}
