//! SLH-DSA-SHA2-128f instantiation (FIPS 205 §11 Table 2).
//!
//! Parameters: n=16, h=66, d=22, h'=3, a=6, k=33, w=16.
//! Sizes: PK_LEN=32, SK_LEN=64, SIG_LEN=17 088.
//!
//! Generated by the `slh_dsa_impl!` macro.
//!
//! # Approved services
//!
//! | Service | Standard | Profile |
//! |---------|----------|---------|
//! | SLH-DSA keygen | FIPS 205 | Unrestricted |
//! | SLH-DSA sign   | FIPS 205 | Unrestricted |
//! | SLH-DSA verify | FIPS 205 | Unrestricted |
//!
//! CNSSP 15 lists no SLH-DSA parameter set, so SHA2-128f is permitted
//! in the FIPS 140-3 Unrestricted profile only. CNSA 2.0 gating is
//! denied at the Service-enum layer in Batch 4.
//!
//! # External vs internal API
//!
//! [`sign`] and [`verify`] implement the FIPS 205 §10.2 / §10.3
//! external API with `ctx` framing (`M' = 0x00 || |ctx| || ctx || M`).
//! [`keygen`] takes a caller-supplied seed, so it is a module-gated
//! wrapper over §9.1 Algorithm 18 rather than §10.1 Algorithm 21,
//! which samples its own randomness.
//! [`keygen_internal`], [`sign_internal`], [`verify_internal`] expose
//! Algorithms 18, 19, 20 directly for CAVP / ACVP harnesses.

#![allow(
    clippy::arithmetic_side_effects,
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::indexing_slicing,
    clippy::integer_division,
    clippy::large_stack_arrays,
    clippy::manual_div_ceil,
    clippy::needless_range_loop,
    clippy::similar_names,
    clippy::too_many_lines,
    clippy::unnecessary_cast,
    clippy::unwrap_used,
    clippy::many_single_char_names,
    dead_code
)]

crate::slh_dsa_impl::slh_dsa_impl! {
    hash_family = sha2;
    n = 16;
    h = 66;
    d = 22;
    a = 6;
    k = 33;
    lg_w = 4;
    svc_keygen = Service::SlhDsaSha2128fKeygen;
    svc_sign = Service::SlhDsaSha2128fSign;
    svc_verify = Service::SlhDsaSha2128fVerify;
    kat_seed_offset = 2u8;
    kat_msg = b"SLH-DSA-SHA2-128f self-test message (FIPS 205)";
    kat_name = "SLH-DSA-SHA2-128f KAT (keygen + sign + verify round-trip, FIPS 205)";
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic)]
mod variant_tests {
    use super::*;

    #[test]
    fn paramset_dispatch_emits_sha256_long_hash() {
        // FIPS 205 §11.2.1: at n=16, H/T/PRF_msg/H_msg use SHA-256
        // (not SHA-512). Macro `__sha2_long_setup!(16)` must select the
        // Sha256 arm. See the CMVP gem in security-policy.md for the
        // macro_rules :literal-hygiene incident that motivated this assert.
        assert_eq!(LONG_PAD, 48, "n=16 long-hash pad must be 48 (SHA-256)");
        assert_eq!(LONG_BLOCK, 64, "n=16 long-hash block must be 64 (SHA-256)");
        assert_eq!(LONG_OUT, 32, "n=16 long-hash out must be 32 (SHA-256)");
    }

    #[test]
    fn key_sizes_match_spec() {
        assert_eq!(PK_LEN, 32);
        assert_eq!(SK_LEN, 64);
        assert_eq!(SIG_LEN, 17_088);
    }

    #[test]
    fn parameter_constants_match_spec() {
        assert_eq!(N, 16);
        assert_eq!(H, 66);
        assert_eq!(D, 22);
        assert_eq!(H_PRIME, 3);
        assert_eq!(A, 6);
        assert_eq!(K, 33);
        assert_eq!(LG_W, 4);
        assert_eq!(W, 16);
        assert_eq!(LEN1, 32);
        assert_eq!(LEN2, 3);
        assert_eq!(LEN, 35);
    }
}
