//! SLH-DSA-SHA2-192f instantiation (FIPS 205 §11 Table 2).
//!
//! Parameters: n=24, h=66, d=22, h'=3, a=8, k=33, w=16.
//! Sizes: PK_LEN=48, SK_LEN=96, SIG_LEN=35 664.
//!
//! Generated by the `slh_dsa_impl!` macro.
//!
//! # Approved services
//!
//! | Service | Standard | Profile |
//! |---------|----------|---------|
//! | SLH-DSA keygen | FIPS 205 | Unrestricted |
//! | SLH-DSA sign   | FIPS 205 | Unrestricted |
//! | SLH-DSA verify | FIPS 205 | Unrestricted |
//!
//! SHA2-192f is permitted in the FIPS 140-3 Unrestricted profile. It is
//! not on the CNSA 2.0 mandate list; CNSA 2.0 gating is denied at the
//! Service-enum layer in Batch 4.
//!
//! # External vs internal API
//!
//! [`keygen`], [`sign`], [`verify`] implement the FIPS 205 §9.2 / §9.3
//! external API with `ctx` framing (`M' = 0x00 || |ctx| || ctx || M`).
//! [`keygen_internal`], [`sign_internal`], [`verify_internal`] expose
//! Algorithms 17, 19, 20 directly for CAVP / ACVP harnesses.

#![allow(
    clippy::arithmetic_side_effects,
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::indexing_slicing,
    clippy::integer_division,
    clippy::large_stack_arrays,
    clippy::manual_div_ceil,
    clippy::needless_range_loop,
    clippy::similar_names,
    clippy::too_many_lines,
    clippy::unnecessary_cast,
    clippy::unwrap_used,
    clippy::many_single_char_names,
    dead_code
)]

crate::slh_dsa_impl::slh_dsa_impl! {
    hash_family = sha2;
    n = 24;
    h = 66;
    d = 22;
    a = 8;
    k = 33;
    lg_w = 4;
    svc_keygen = Service::SlhDsaSha2192fKeygen;
    svc_sign = Service::SlhDsaSha2192fSign;
    svc_verify = Service::SlhDsaSha2192fVerify;
    kat_seed_offset = 4u8;
    kat_msg = b"SLH-DSA-SHA2-192f self-test message (FIPS 205)";
    kat_name = "SLH-DSA-SHA2-192f KAT (keygen + sign + verify round-trip, FIPS 205)";
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic)]
mod variant_tests {
    use super::*;

    #[test]
    fn paramset_dispatch_emits_sha512_long_hash() {
        // FIPS 205 §10.1 Table 5: at n=24/32, H/T/PRF_msg/H_msg use
        // SHA-512 truncated. `__sha2_long_setup!($n)` must hit the
        // catch-all arm. See CMVP gem in security-policy.md for the
        // macro_rules :literal-hygiene incident that motivated this assert.
        assert_eq!(LONG_PAD, 104, "long-hash pad must be 128-N (SHA-512)");
        assert_eq!(LONG_BLOCK, 128, "long-hash block must be 128 (SHA-512)");
        assert_eq!(LONG_OUT, 64, "long-hash out must be 64 (SHA-512)");
    }

    #[test]
    fn key_sizes_match_spec() {
        assert_eq!(PK_LEN, 48);
        assert_eq!(SK_LEN, 96);
        assert_eq!(SIG_LEN, 35_664);
    }

    #[test]
    fn parameter_constants_match_spec() {
        assert_eq!(N, 24);
        assert_eq!(H, 66);
        assert_eq!(D, 22);
        assert_eq!(H_PRIME, 3);
        assert_eq!(A, 8);
        assert_eq!(K, 33);
        assert_eq!(LG_W, 4);
        assert_eq!(W, 16);
        assert_eq!(LEN1, 48);
        assert_eq!(LEN2, 3);
        assert_eq!(LEN, 51);
    }
}
