[package]
name = "fips-ecdsa"
description = "ECDSA (P-256, P-384, P-521) per FIPS 186-5"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
fips-module = { path = "../fips-module" }
fips-sha = { path = "../fips-sha" }
fips-drbg = { path = "../fips-drbg" }
