[package]
name = "oxicrypt-kdf"
description = "SP 800-108r1, SP 800-56Cr2 and HKDF key derivation functions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
oxicrypt-module = { path = "../oxicrypt-module" }
oxicrypt-sha = { path = "../oxicrypt-sha" }
oxicrypt-hmac = { path = "../oxicrypt-hmac" }
oxicrypt-test-vectors = { path = "../oxicrypt-test-vectors" }
oxicrypt-zeroize = { path = "../oxicrypt-zeroize" }
