//! ML-KEM-768 instantiation (FIPS 203 Table 2).
//!
//! Parameters: k = 3, η₁ = η₂ = 2, dᵤ = 10, dᵥ = 4.
//! Sizes: EK_LEN = 1184, DK_LEN = 2400, CT_LEN = 1088.
//!
//! Generated by the [`ml_kem_impl!`](crate::ml_kem_impl) macro.
//!
//! # KAT seeds
//!
//! Seeds are fresh deterministic constants generated specifically
//! for this variant. The self-test exercises the round-trip +
//! implicit-rejection oracle identical to other variants.
//!
//! # CNSA gating
//!
//! ML-KEM-768 is **not** part of CNSA 2.0 (which mandates ML-KEM-1024)
//! and is **not** in the CNSA 1.0 suite either. The
//! [`Service::MlKem768Keygen`] / `Encaps` / `Decaps` variants are
//! permitted only under [`oxicrypt_module::AlgorithmProfile::Unrestricted`].

#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::similar_names,
    dead_code
)]

crate::ml_kem_impl::ml_kem_impl! {
    k = 3;
    eta1 = 2;
    eta2 = 2;
    du = 10;
    dv = 4;
    svc_keygen = Service::MlKem768Keygen;
    svc_encaps = Service::MlKem768Encaps;
    svc_decaps = Service::MlKem768Decaps;
    kat_d = [
        0x07, 0x68, 0xa1, 0xb2, 0xc3, 0xd4, 0xe5, 0xf6, 0x07, 0x18, 0x29, 0x3a, 0x4b, 0x5c, 0x6d,
        0x7e, 0x8f, 0x90, 0xa1, 0xb2, 0xc3, 0xd4, 0xe5, 0xf6, 0x07, 0x18, 0x29, 0x3a, 0x4b, 0x5c,
        0x6d, 0x7e,
    ];
    kat_z = [
        0xb7, 0x68, 0x22, 0x44, 0x66, 0x88, 0xaa, 0xcc, 0xee, 0x11, 0x33, 0x55, 0x77, 0x99, 0xbb,
        0xdd, 0xff, 0x10, 0x32, 0x54, 0x76, 0x98, 0xba, 0xdc, 0xfe, 0x21, 0x43, 0x65, 0x87, 0xa9,
        0xcb, 0xed,
    ];
    kat_m = [
        0x37, 0x68, 0xff, 0xee, 0x42, 0xde, 0xad, 0xbe, 0xef, 0xca, 0xfe, 0xba, 0xbe, 0x01, 0x23,
        0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10, 0xa5,
        0xa5, 0xa5,
    ];
    kat_name = "ML-KEM-768 KAT (round-trip + implicit rejection, FIPS 203)";
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]
mod tests {
    use super::*;

    #[test]
    fn self_test_passes() {
        self_test().unwrap();
    }

    #[test]
    fn round_trip_basic() {
        let d = [0x42u8; 32];
        let z = [0x77u8; 32];
        let m = [0xABu8; 32];

        let (ek, dk) = keygen_internal(&d, &z).unwrap();
        let (k, ct) = encaps_internal(&ek, &m);
        let k2 = decaps_internal(&dk, &ct);
        assert_eq!(k, k2, "round-trip failed: shared secrets differ");
    }

    #[test]
    fn implicit_rejection_different_key() {
        let d = [0x01u8; 32];
        let z = [0x02u8; 32];
        let m = [0x03u8; 32];

        let (ek, dk) = keygen_internal(&d, &z).unwrap();
        let (k, mut ct) = encaps_internal(&ek, &m);
        ct[10] ^= 0xFF;
        let k_bad = decaps_internal(&dk, &ct);
        assert_ne!(k, k_bad);
    }

    #[test]
    fn implicit_rejection_matches_j_z_c() {
        use oxicrypt_xof::Shake256;

        let d = [0x05u8; 32];
        let z = [0x06u8; 32];
        let m = [0x07u8; 32];

        let (ek, dk) = keygen_internal(&d, &z).unwrap();
        let (_k, mut ct) = encaps_internal(&ek, &m);
        ct[42] ^= 0xA5;

        let mut j = Shake256::new_internal();
        j.update(&z);
        j.update(&ct);
        j.finalize();
        let mut expected_k_bar = [0u8; 32];
        j.squeeze(&mut expected_k_bar);

        let actual = decaps_internal(&dk, &ct);
        assert_eq!(
            actual, expected_k_bar,
            "implicit rejection key must equal J(z || c) byte-exactly per FIPS 203 §7.3"
        );
    }

    #[test]
    fn key_sizes_match_spec() {
        // FIPS 203 Table 2: ML-KEM-768
        assert_eq!(EK_LEN, 1184);
        assert_eq!(DK_LEN, 2400);
        assert_eq!(CT_LEN, 1088);
        assert_eq!(SHARED_SECRET_LEN, 32);
    }

    #[test]
    fn parameter_constants_match_spec() {
        assert_eq!(K, 3);
        assert_eq!(ETA1, 2);
        assert_eq!(ETA2, 2);
        assert_eq!(DU, 10);
        assert_eq!(DV, 4);
    }

    #[test]
    fn determinism() {
        let (ek1, dk1) = keygen_internal(&KAT_D, &KAT_Z_SEED).unwrap();
        let (ek2, dk2) = keygen_internal(&KAT_D, &KAT_Z_SEED).unwrap();
        assert_eq!(ek1, ek2);
        assert_eq!(dk1, dk2);
    }
}
