//! ML-KEM-1024 instantiation (FIPS 203 Table 2).
//!
//! Parameters: k = 4, η₁ = η₂ = 2, dᵤ = 11, dᵥ = 5.
//! Sizes: EK_LEN = 1568, DK_LEN = 3168, CT_LEN = 1568.
//!
//! Generated by the [`ml_kem_impl!`](crate::ml_kem_impl) macro.
//! KAT seeds preserved verbatim from the pre-refactor crate so the
//! existing ACVTS demo replay (session 727796) and the
//! `implicit_rejection_matches_j_z_c` byte-exact oracle continue to
//! pass byte-for-byte.

#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::similar_names,
    dead_code
)]

crate::ml_kem_impl::ml_kem_impl! {
    k = 4;
    eta1 = 2;
    eta2 = 2;
    du = 11;
    dv = 5;
    svc_keygen = Service::MlKem1024Keygen;
    svc_encaps = Service::MlKem1024Encaps;
    svc_decaps = Service::MlKem1024Decaps;
    kat_d = [
        0x7f, 0x9c, 0x2b, 0xa4, 0xe8, 0x8f, 0x82, 0x7d, 0x61, 0x60, 0x45, 0x50, 0x76, 0x05, 0x85,
        0x3e, 0xd7, 0x3b, 0x80, 0x93, 0xf6, 0xef, 0xbc, 0x88, 0xeb, 0x1a, 0x6e, 0xaf, 0xfa, 0x28,
        0x4f, 0x01,
    ];
    kat_z = [
        0xac, 0xcd, 0x06, 0xa5, 0x3d, 0x9b, 0x0c, 0xff, 0x59, 0xfa, 0x11, 0x68, 0x42, 0x7b, 0x31,
        0x9e, 0x2b, 0x6a, 0x9f, 0xd7, 0x04, 0xe9, 0x56, 0xd4, 0x3a, 0x08, 0xc4, 0x7e, 0x01, 0x15,
        0x67, 0xbc,
    ];
    kat_m = [
        0x14, 0x7c, 0x03, 0xf7, 0xa5, 0xbe, 0xbb, 0xa4, 0x06, 0xc8, 0xfa, 0xe1, 0x87, 0x4d, 0x7f,
        0x13, 0xc8, 0x0e, 0xfe, 0x79, 0xa3, 0xa9, 0xa8, 0x74, 0xcc, 0x09, 0xfe, 0x76, 0xf6, 0x99,
        0x76, 0x15,
    ];
    kat_name = "ML-KEM-1024 KAT (round-trip + implicit rejection, FIPS 203)";
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]
mod tests {
    use super::*;
    use oxicrypt_module::{KatEntry, initialize_with_tests};

    /// Stands in for the pre-operational integrity test.
    ///
    /// A `cargo test` binary is never signed, so the real integrity test
    /// cannot pass inside one. The module requires an integrity group to
    /// initialise at all, so a test that needs a gated service declares
    /// this stub — visibly, at the call site — rather than the module
    /// offering any way to skip the requirement.
    const UNSIGNED_TEST_BINARY: &[KatEntry] = &[KatEntry {
        name: "integrity not verifiable in an unsigned test binary",
        run: || Ok(()),
    }];

    fn ensure_initialized() {
        let _ = initialize_with_tests(
            UNSIGNED_TEST_BINARY,
            &[KatEntry {
                name: "ml-kem-1024-bootstrap",
                run: self_test,
            }],
        );
    }

    #[test]
    fn self_test_passes() {
        self_test().unwrap();
    }

    #[test]
    fn round_trip_basic() {
        let d = [0x42u8; 32];
        let z = [0x77u8; 32];
        let m = [0xABu8; 32];

        let (ek, dk) = keygen_internal(&d, &z).unwrap();
        let (k, ct) = encaps_internal(&ek, &m);
        let k2 = decaps_internal(&dk, &ct);
        assert_eq!(k, k2, "round-trip failed: shared secrets differ");
    }

    #[test]
    fn implicit_rejection_different_key() {
        let d = [0x01u8; 32];
        let z = [0x02u8; 32];
        let m = [0x03u8; 32];

        let (ek, dk) = keygen_internal(&d, &z).unwrap();
        let (k, mut ct) = encaps_internal(&ek, &m);
        ct[10] ^= 0xFF; // tamper
        let k_bad = decaps_internal(&dk, &ct);
        assert_ne!(
            k, k_bad,
            "implicit rejection failed: keys match after tamper"
        );
    }

    /// Tampered-ciphertext output must match the spec's `K̄ = J(z || c)`
    /// (FIPS 203 §7.3, where `J = SHAKE-256` truncated to 32 bytes)
    /// **byte-exactly** — not merely "different from the valid path".
    ///
    /// The weaker `assert_ne` guard above passes for a wide range of
    /// incorrect implementations (including a bug where `ct_select_32`
    /// only flipped LSBs of `k_prime` instead of selecting `k_bar`
    /// whole — different from `k_prime`, but also not equal to
    /// `J(z || c)`). This test pins the implicit-rejection branch
    /// against the spec-defined oracle, matching how ACVTS grades it.
    #[test]
    fn implicit_rejection_matches_j_z_c() {
        use oxicrypt_xof::Shake256;

        let d = [0x05u8; 32];
        let z = [0x06u8; 32];
        let m = [0x07u8; 32];

        let (ek, dk) = keygen_internal(&d, &z).unwrap();
        let (_k, mut ct) = encaps_internal(&ek, &m);
        ct[42] ^= 0xA5; // tamper to force implicit rejection

        let mut j = Shake256::new_internal();
        j.update(&z);
        j.update(&ct);
        j.finalize();
        let mut expected_k_bar = [0u8; 32];
        j.squeeze(&mut expected_k_bar);

        let actual = decaps_internal(&dk, &ct);
        assert_eq!(
            actual, expected_k_bar,
            "implicit rejection key must equal J(z || c) byte-exactly per FIPS 203 §7.3"
        );
    }

    #[test]
    fn different_randomness_different_keys() {
        let d1 = [0x10u8; 32];
        let z1 = [0x20u8; 32];
        let d2 = [0x30u8; 32];
        let z2 = [0x40u8; 32];

        let (ek1, _) = keygen_internal(&d1, &z1).unwrap();
        let (ek2, _) = keygen_internal(&d2, &z2).unwrap();
        assert_ne!(ek1, ek2, "different seeds should produce different keys");
    }

    #[test]
    fn key_sizes_match_spec() {
        assert_eq!(EK_LEN, 1568);
        assert_eq!(DK_LEN, 3168);
        assert_eq!(CT_LEN, 1568);
        assert_eq!(SHARED_SECRET_LEN, 32);
    }

    #[test]
    fn gated_api_requires_operational() {
        ensure_initialized();
        let d = [0u8; 32];
        let z = [0u8; 32];
        let result = keygen(&d, &z);
        assert!(result.is_ok());
    }

    #[test]
    fn determinism() {
        let (ek1, dk1) = keygen_internal(&KAT_D, &KAT_Z_SEED).unwrap();
        let (ek2, dk2) = keygen_internal(&KAT_D, &KAT_Z_SEED).unwrap();
        assert_eq!(ek1, ek2);
        assert_eq!(dk1, dk2);

        let (k1, ct1) = encaps_internal(&ek1, &KAT_M);
        let (k2, ct2) = encaps_internal(&ek2, &KAT_M);
        assert_eq!(k1, k2);
        assert_eq!(ct1, ct2);
    }
}
