#!/usr/bin/env python3
"""Generate per-pair Rust files invoking the lms_impl! macro.

Each pair file is a thin shim — it imports Service, the hash adapter,
and the macro, then calls the macro with the pair's RFC 8554 §A.1+§A.2
constants. The macro emits keygen/sign/verify/KAT for that exact pair.

Per-(N, W) derived constants come from RFC 8554 §A.1 directly (no
runtime computation — the values are fixed by the family).
"""
import sys
from pathlib import Path

SRC_DIR = (
    Path.home()
    / "carakastan"
    / "Projects"
    / "OxiCrypt"
    / "oxicrypt"
    / ".worktrees"
    / "lms-expansion"
    / "crates"
    / "oxicrypt-lms"
    / "src"
)

# (N, W) → (U, V, P, LS) per RFC 8554 §A.1 + RFC 8708 §3.1/§4.1.
UV_TABLE = {
    (32, 1): (256, 9, 265, 7),
    (32, 2): (128, 5, 133, 6),
    (32, 4): (64, 3, 67, 4),
    (32, 8): (32, 2, 34, 0),
    (24, 1): (192, 8, 200, 8),
    (24, 2): (96, 5, 101, 6),
    (24, 4): (48, 3, 51, 4),
    (24, 8): (24, 2, 26, 0),
}

# LMS typecode per RFC 8554 §A.2 + RFC 8708.
# (family, M, H) → 32-bit typecode.
LMS_TYPECODES = {
    ("sha256", 32, 5):  0x05,
    ("sha256", 32, 10): 0x06,
    ("sha256", 32, 15): 0x07,
    ("sha256", 32, 20): 0x08,
    ("sha256", 32, 25): 0x09,
    ("sha256", 24, 5):  0x0a,
    ("sha256", 24, 10): 0x0b,
    ("sha256", 24, 15): 0x0c,
    ("sha256", 24, 20): 0x0d,
    ("sha256", 24, 25): 0x0e,
    ("shake",  32, 5):  0x0f,
    ("shake",  32, 10): 0x10,
    ("shake",  32, 15): 0x11,
    ("shake",  32, 20): 0x12,
    ("shake",  32, 25): 0x13,
    ("shake",  24, 5):  0x14,
    ("shake",  24, 10): 0x15,
    ("shake",  24, 15): 0x16,
    ("shake",  24, 20): 0x17,
    ("shake",  24, 25): 0x18,
}

# LMOTS typecode per RFC 8554 §A.1 + RFC 8708.
# (family, N, W) → 32-bit typecode.
LMOTS_TYPECODES = {
    ("sha256", 32, 1): 0x01,
    ("sha256", 32, 2): 0x02,
    ("sha256", 32, 4): 0x03,
    ("sha256", 32, 8): 0x04,
    ("sha256", 24, 1): 0x05,
    ("sha256", 24, 2): 0x06,
    ("sha256", 24, 4): 0x07,
    ("sha256", 24, 8): 0x08,
    ("shake",  32, 1): 0x09,
    ("shake",  32, 2): 0x0a,
    ("shake",  32, 4): 0x0b,
    ("shake",  32, 8): 0x0c,
    ("shake",  24, 1): 0x0d,
    ("shake",  24, 2): 0x0e,
    ("shake",  24, 4): 0x0f,
    ("shake",  24, 8): 0x10,
}

ADAPTER = {
    ("sha256", 32): "Sha256N32",
    ("sha256", 24): "Sha256N24",
    ("shake",  32): "Shake256N32",
    ("shake",  24): "Shake256N24",
}

ALLOWED_FAMILIES = sys.argv[1:] if len(sys.argv) > 1 else ["sha256_m32"]
EXCLUDE = {"lms_sha256_m32_h10_w4"}  # baseline already shipped in B1

TEMPLATE = '''//! {pair_human} instantiation.
//!
//! Parameters: hash = {hash_human}, N = {n}, H = {h} ({signatures}
//! signatures), W = {w} (Winternitz). Derived (RFC 8554 §4.1):
//! U = {u}, V = {v}, P = {p}, LS = {ls}.
//!
//! Generated by [`lms_impl!`](crate::lms_impl). External KAT grounding:
//! one passing sigVer test case vendored from
//! `usnistgov/ACVP-Server @ 112690e8` (vsId-tg derived per pair), run
//! by `tests/nist_kat_all_pairs.rs`.

use oxicrypt_module::Service;

crate::lms_impl::lms_impl! {{
    hasher = crate::hash::{adapter};
    n = {n};
    h = {h};
    w = {w};
    u = {u};
    v = {v};
    p = {p};
    ls = {ls};
    lms_type = 0x0000_{lms_type:04x};
    lmots_type = 0x0000_{lmots_type:04x};
    svc_sign = Service::LmsSign;
    svc_verify = Service::LmsVerify;
    kat_xi = [
        0x4c, 0x4d, 0x53, 0x2d, 0x4b, 0x41, 0x54, 0x2d, // "LMS-KAT-"
        0x53, 0x50, 0x38, 0x30, 0x30, 0x2d, 0x32, 0x30, // "SP800-20"
        0x38, 0x2d, 0x6f, 0x78, 0x69, 0x63, 0x72, 0x79, // "8-oxicry"
        0x70, 0x74, 0x2d, 0x76, 0x30, 0x2e, 0x30, 0x2e, // "pt-v0.0."
    ];
    kat_msg = b"LMS self-test message for SP 800-208 / FIPS 140-3 compliance";
    kat_name = "LMS KAT ({pair_human} keygen+sign+verify round-trip, SP 800-208)";
}}
'''


def main():
    pairs_written = []
    for (fam, m, h), lms_type in LMS_TYPECODES.items():
        if f"{fam}_m{m}" not in ALLOWED_FAMILIES:
            continue
        for w in (1, 2, 4, 8):
            lmots_type = LMOTS_TYPECODES[(fam, m, w)]
            u, v, p, ls = UV_TABLE[(m, w)]
            slug = f"lms_{fam}_m{m}_h{h}_w{w}"
            if slug in EXCLUDE:
                continue
            adapter = ADAPTER[(fam, m)]
            hash_human = {"sha256": "SHA-256", "shake": "SHAKE-256"}[fam]
            pair_human = f"LMS_{fam.upper().replace('SHA256','SHA256')}_M{m}_H{h} / LMOTS_{fam.upper().replace('SHAKE','SHAKE').replace('SHA256','SHA256')}_N{m}_W{w}"
            # Rebuild canonical NIST naming for human-readable strings:
            fam_caps = {"sha256": "SHA256", "shake": "SHAKE"}[fam]
            pair_human = f"LMS_{fam_caps}_M{m}_H{h} / LMOTS_{fam_caps}_N{m}_W{w}"
            content = TEMPLATE.format(
                pair_human=pair_human,
                hash_human=hash_human,
                adapter=adapter,
                n=m,
                h=h,
                w=w,
                u=u,
                v=v,
                p=p,
                ls=ls,
                lms_type=lms_type,
                lmots_type=lmots_type,
                signatures=2**h,
            )
            out = SRC_DIR / f"{slug}.rs"
            out.write_text(content)
            pairs_written.append(slug)

    print(f"families={ALLOWED_FAMILIES}")
    print(f"pair files written: {len(pairs_written)}")
    for slug in sorted(pairs_written):
        print(f"  {slug}")


if __name__ == "__main__":
    main()
