//! Fixed-width 1536-bit unsigned big integer.
//!
//! CRT half-width for RSA-3072: each prime factor `p`, `q` of a
//! 3072-bit modulus is 1536 bits. This module parallels
//! [`crate::bigint1024`] but at 24-limb width. The core constant-time
//! arithmetic is generated by `define_bigint_type`;
//! keygen-specific helpers (`widening_mul`, `shr1`, `rem_u64`, etc.)
//! are added below.

#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::cast_lossless,
    clippy::similar_names,
    clippy::return_self_not_must_use,
    clippy::needless_range_loop,
    clippy::many_single_char_names,
    dead_code
)]

use crate::bigint_impl::define_bigint_type;
use crate::bigint3072::{LIMBS as LIMBS3072, U3072};

define_bigint_type! {
    /// A 1536-bit unsigned integer (CRT half for RSA-3072).
    pub struct U1536;
    limbs = 24;
    bytes = 192;
}

// ---- Keygen-specific helpers (mirror of U1024's extras) ----

impl U1536 {
    /// The multiplicative identity (one).
    pub const ONE: U1536 = {
        let mut limbs = [0u64; LIMBS];
        limbs[0] = 1;
        U1536 { limbs }
    };

    /// Returns `1` iff `self == 1`, else `0`.
    pub fn is_one(&self) -> u8 {
        let mut acc: u64 = self.limbs[0] ^ 1;
        for i in 1..LIMBS {
            acc |= self.limbs[i];
        }
        let nz = (acc | acc.wrapping_neg()) >> 63;
        (1 ^ (nz as u8)) & 1
    }

    /// Parity bit: `1` if odd, `0` if even.
    pub fn is_odd(&self) -> u8 {
        (self.limbs[0] & 1) as u8
    }

    /// Divide by two (shift right by one bit). Used by binary
    /// extended GCD on public inputs only.
    pub fn shr1(&self) -> U1536 {
        let mut limbs = [0u64; LIMBS];
        let mut carry: u64 = 0;
        for i in (0..LIMBS).rev() {
            let v = self.limbs[i];
            limbs[i] = (v >> 1) | (carry << 63);
            carry = v & 1;
        }
        U1536 { limbs }
    }

    /// Modular reduction by a small `u64`. Used for trial-division
    /// sieve during prime generation.
    pub fn rem_u64(&self, m: u64) -> u64 {
        debug_assert!(m > 0);
        let mut rem: u128 = 0;
        for i in (0..LIMBS).rev() {
            rem = ((rem << 64) | self.limbs[i] as u128) % (m as u128);
        }
        rem as u64
    }

    /// Widening multiply: `self × other → U3072`. Used once per
    /// keygen run to form `n = p · q`.
    pub fn widening_mul(&self, other: &U1536) -> U3072 {
        let mut out = [0u64; LIMBS3072];
        for i in 0..LIMBS {
            let mut carry: u64 = 0;
            for j in 0..LIMBS {
                let prod = (self.limbs[i] as u128) * (other.limbs[j] as u128)
                    + (out[i + j] as u128)
                    + (carry as u128);
                out[i + j] = prod as u64;
                carry = (prod >> 64) as u64;
            }
            out[i + LIMBS] = carry;
        }
        U3072 { limbs: out }
    }

    /// Widening add of a small `u64`, returning `(sum, carry_out)`.
    pub fn adding_u64(&self, addend: u64) -> (U1536, u64) {
        let mut limbs = self.limbs;
        let (s, c0) = limbs[0].overflowing_add(addend);
        limbs[0] = s;
        let mut carry: u64 = u64::from(c0);
        for i in 1..LIMBS {
            if carry == 0 {
                break;
            }
            let (s, c) = limbs[i].overflowing_add(carry);
            limbs[i] = s;
            carry = u64::from(c);
        }
        (U1536 { limbs }, carry)
    }

    /// Subtract a small `u64`, returning `(diff, borrow_out)`.
    pub fn subtracting_u64(&self, sub: u64) -> (U1536, u64) {
        let mut limbs = self.limbs;
        let (d, b0) = limbs[0].overflowing_sub(sub);
        limbs[0] = d;
        let mut borrow: u64 = u64::from(b0);
        for i in 1..LIMBS {
            if borrow == 0 {
                break;
            }
            let (d, b) = limbs[i].overflowing_sub(borrow);
            limbs[i] = d;
            borrow = u64::from(b);
        }
        (U1536 { limbs }, borrow)
    }

    /// Zero-extend to a [`U3072`].
    pub fn zero_extend(&self) -> U3072 {
        let mut limbs = [0u64; LIMBS3072];
        limbs[..LIMBS].copy_from_slice(&self.limbs);
        U3072 { limbs }
    }
}

/// Binary extended GCD producing the modular inverse of `a` mod `m`,
/// where `m` is odd. Returns `None` if `gcd(a, m) != 1`.
///
/// This is the textbook "plus-minus" variant — identical logic to
/// [`crate::bigint1024::modinv_odd`] but at 24-limb width.
///
/// **Data-dependent** control flow — not suitable for secret operands.
/// RSA keygen only calls this with the public exponent `e` and the
/// public `λ(n)`. See [`crate::bigint1024::modinv_odd`] for the full
/// design rationale and top-bit-set limitation caveat.
pub fn modinv_odd(a: &U1536, m: &U1536) -> Option<U1536> {
    debug_assert!(m.is_odd() == 1);
    if a.is_zero() == 1 {
        return None;
    }
    let mut u = *a;
    let mut v = *m;
    let mut x1 = U1536::ONE;
    let mut x2 = U1536::ZERO;

    // Upper bound: ~2 * 1536 = 3072 iterations; use 6144 for margin.
    for _ in 0..6144 {
        if u.is_zero() == 1 {
            if v.ct_eq(&U1536::ONE) != 1 {
                return None;
            }
            return Some(x2);
        }
        if v.is_zero() == 1 {
            if u.ct_eq(&U1536::ONE) != 1 {
                return None;
            }
            return Some(x1);
        }

        while u.is_odd() == 0 {
            u = u.shr1();
            if x1.is_odd() == 1 {
                let (sum, _) = x1.adding(m);
                x1 = sum.shr1();
            } else {
                x1 = x1.shr1();
            }
        }
        while v.is_odd() == 0 {
            v = v.shr1();
            if x2.is_odd() == 1 {
                let (sum, _) = x2.adding(m);
                x2 = sum.shr1();
            } else {
                x2 = x2.shr1();
            }
        }

        if u.ct_lt(&v) == 0 {
            u = u.subtracting(&v).0;
            if x1.ct_lt(&x2) == 1 {
                let (s, _) = x1.adding(m);
                x1 = s.subtracting(&x2).0;
            } else {
                x1 = x1.subtracting(&x2).0;
            }
        } else {
            v = v.subtracting(&u).0;
            if x2.ct_lt(&x1) == 1 {
                let (s, _) = x2.adding(m);
                x2 = s.subtracting(&x1).0;
            } else {
                x2 = x2.subtracting(&x1).0;
            }
        }
    }
    None
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic, clippy::expect_used)]
mod tests {
    use super::*;

    fn from_u64(x: u64) -> U1536 {
        let mut limbs = [0u64; LIMBS];
        limbs[0] = x;
        U1536 { limbs }
    }

    #[test]
    fn zero_roundtrips() {
        let z = U1536::ZERO;
        assert_eq!(z.is_zero(), 1);
        assert_eq!(z.is_one(), 0);
        let b = z.to_be_bytes();
        assert_eq!(b, [0u8; BYTES]);
        assert_eq!(U1536::from_be_bytes(&b), z);
    }

    #[test]
    fn one_is_one() {
        assert_eq!(U1536::ONE.is_one(), 1);
        assert_eq!(U1536::ONE.is_odd(), 1);
    }

    #[test]
    fn roundtrip_all_ones() {
        let mut bytes = [0u8; BYTES];
        bytes.fill(0xff);
        let x = U1536::from_be_bytes(&bytes);
        assert_eq!(x.limbs, [0xffff_ffff_ffff_ffff; LIMBS]);
        assert_eq!(x.to_be_bytes(), bytes);
        assert_eq!(x.is_zero(), 0);
    }

    #[test]
    fn big_endian_top_bit() {
        let mut bytes = [0u8; BYTES];
        bytes[0] = 0x80;
        let x = U1536::from_be_bytes(&bytes);
        assert_eq!(x.limbs[LIMBS - 1], 0x8000_0000_0000_0000);
        for i in 0..LIMBS - 1 {
            assert_eq!(x.limbs[i], 0);
        }
    }

    #[test]
    fn ct_lt_orders_correctly() {
        let a = from_u64(1);
        let b = from_u64(2);
        assert_eq!(a.ct_lt(&b), 1);
        assert_eq!(b.ct_lt(&a), 0);
        assert_eq!(a.ct_lt(&a), 0);
    }

    #[test]
    fn adding_wraps_with_carry() {
        let ones = U1536 {
            limbs: [0xffff_ffff_ffff_ffff; LIMBS],
        };
        let one = from_u64(1);
        let (sum, carry) = ones.adding(&one);
        assert_eq!(sum, U1536::ZERO);
        assert_eq!(carry, 1);
    }

    #[test]
    fn widening_mul_small() {
        let three = from_u64(3);
        let five = from_u64(5);
        let prod = three.widening_mul(&five);
        assert_eq!(prod.limbs[0], 15);
        for i in 1..LIMBS3072 {
            assert_eq!(prod.limbs[i], 0);
        }
    }

    #[test]
    fn widening_mul_spans_upper_half() {
        let mut hi_bit = U1536::ZERO;
        hi_bit.limbs[LIMBS - 1] = 1u64 << 63;
        let two = from_u64(2);
        let prod = hi_bit.widening_mul(&two);
        for i in 0..LIMBS {
            assert_eq!(prod.limbs[i], 0, "low half limb {i}");
        }
        assert_eq!(prod.limbs[LIMBS], 1);
    }

    #[test]
    fn rem_u64_small_cases() {
        let x = from_u64(100);
        assert_eq!(x.rem_u64(7), 2);
        assert_eq!(x.rem_u64(100), 0);
    }

    #[test]
    fn shr1_halves() {
        let x = from_u64(42);
        assert_eq!(x.shr1(), from_u64(21));
    }

    #[test]
    fn modinv_small_prime() {
        let three = from_u64(3);
        let eleven = from_u64(11);
        let inv = modinv_odd(&three, &eleven).unwrap();
        assert_eq!(inv, from_u64(4));
    }

    #[test]
    fn modinv_65537_mod_large_odd() {
        let m_small: u64 = 3 * 5 * 7 * 11 * 13 * 17 * 19 * 23 * 29 * 31;
        let e = from_u64(65537);
        let m = from_u64(m_small);
        let inv = modinv_odd(&e, &m).unwrap();
        let prod = 65537u128 * (inv.limbs[0] as u128);
        assert_eq!((prod % (m_small as u128)) as u64, 1);
    }

    #[test]
    fn modinv_rejects_noncoprime() {
        let six = from_u64(6);
        let nine = from_u64(9);
        assert!(modinv_odd(&six, &nine).is_none());
    }

    #[test]
    fn nibble_reads_little_endian() {
        let mut limbs = [0u64; LIMBS];
        limbs[0] = 0xfedc_ba98_7654_3210;
        let x = U1536 { limbs };
        for i in 0..16 {
            assert_eq!(x.nibble(i), i as u8);
        }
    }

    #[test]
    fn ct_sub_if_ge_works() {
        let a = from_u64(5);
        let b = from_u64(7);
        assert_eq!(a.ct_sub_if_ge(&b), a);
        assert_eq!(b.ct_sub_if_ge(&a), from_u64(2));
    }
}
