//! Fixed-width 4096-bit unsigned big integer.
//!
//! Full-width container for the RSA-4096 modulus `n = p · q` where
//! each prime factor is 2048 bits. Parallel to [`crate::bigint2048`]
//! but at 64-limb width. The core constant-time arithmetic is
//! generated by `define_bigint_type`.
//!
//! We intentionally do **not** implement `U4096 × U4096 → U8192`:
//! the CIOS Montgomery multiplier in [`crate::mont4096`] interleaves
//! reduction with multiplication and never materializes an 8192-bit
//! intermediate product.

#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::cast_lossless,
    clippy::similar_names,
    clippy::return_self_not_must_use,
    clippy::needless_range_loop,
    clippy::many_single_char_names,
    dead_code
)]

use crate::bigint_impl::define_bigint_type;

define_bigint_type! {
    /// A 4096-bit unsigned integer.
    pub struct U4096;
    limbs = 64;
    bytes = 512;
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn zero_roundtrips() {
        let z = U4096::ZERO;
        assert_eq!(z.is_zero(), 1);
        let bytes = z.to_be_bytes();
        assert_eq!(bytes, [0u8; BYTES]);
        let back = U4096::from_be_bytes(&bytes);
        assert_eq!(back, z);
    }

    #[test]
    fn roundtrip_all_ones() {
        let mut bytes = [0u8; BYTES];
        bytes.fill(0xff);
        let x = U4096::from_be_bytes(&bytes);
        assert_eq!(x.limbs, [0xffff_ffff_ffff_ffff; LIMBS]);
        assert_eq!(x.to_be_bytes(), bytes);
    }

    #[test]
    fn big_endian_top_bit() {
        let mut bytes = [0u8; BYTES];
        bytes[0] = 0x80;
        let x = U4096::from_be_bytes(&bytes);
        assert_eq!(x.limbs[LIMBS - 1], 0x8000_0000_0000_0000);
        for i in 0..LIMBS - 1 {
            assert_eq!(x.limbs[i], 0);
        }
    }

    #[test]
    fn ct_lt_orders_correctly() {
        let mut a_bytes = [0u8; BYTES];
        let mut b_bytes = [0u8; BYTES];
        a_bytes[BYTES - 1] = 0x01;
        b_bytes[BYTES - 1] = 0x02;
        let a = U4096::from_be_bytes(&a_bytes);
        let b = U4096::from_be_bytes(&b_bytes);
        assert_eq!(a.ct_lt(&b), 1);
        assert_eq!(b.ct_lt(&a), 0);
    }

    #[test]
    fn adding_wraps_with_carry() {
        let ones = U4096 { limbs: [0xffff_ffff_ffff_ffff; LIMBS] };
        let mut one_bytes = [0u8; BYTES];
        one_bytes[BYTES - 1] = 1;
        let one = U4096::from_be_bytes(&one_bytes);
        let (sum, carry) = ones.adding(&one);
        assert_eq!(sum, U4096::ZERO);
        assert_eq!(carry, 1);
    }

    #[test]
    fn subtracting_zero_minus_one_borrows() {
        let mut one_bytes = [0u8; BYTES];
        one_bytes[BYTES - 1] = 1;
        let one = U4096::from_be_bytes(&one_bytes);
        let (diff, borrow) = U4096::ZERO.subtracting(&one);
        assert_eq!(diff, U4096 { limbs: [0xffff_ffff_ffff_ffff; LIMBS] });
        assert_eq!(borrow, 1);
    }

    #[test]
    fn conditional_select_picks_a_or_b() {
        let a = U4096 { limbs: [0xaa; LIMBS] };
        let b = U4096 { limbs: [0x55; LIMBS] };
        assert_eq!(U4096::conditional_select(u64::MAX, &a, &b), a);
        assert_eq!(U4096::conditional_select(0, &a, &b), b);
    }

    #[test]
    fn nibble_reads_little_endian() {
        let mut limbs = [0u64; LIMBS];
        limbs[0] = 0xfedc_ba98_7654_3210;
        let x = U4096 { limbs };
        for i in 0..16 {
            assert_eq!(x.nibble(i), i as u8);
        }
    }

    #[test]
    fn ct_sub_if_ge_works() {
        let mut a = [0u8; BYTES];
        let mut b = [0u8; BYTES];
        a[BYTES - 1] = 5;
        b[BYTES - 1] = 7;
        let av = U4096::from_be_bytes(&a);
        let bv = U4096::from_be_bytes(&b);
        assert_eq!(av.ct_sub_if_ge(&bv), av);
        let mut expect = [0u8; BYTES];
        expect[BYTES - 1] = 2;
        assert_eq!(bv.ct_sub_if_ge(&av), U4096::from_be_bytes(&expect));
    }
}
