//! RSA-3072 key operations — sign, verify, encrypt, decrypt, keygen.
//!
//! Full implementation of the RSA-3072 service layer, replacing the
//! earlier stubs in `rsa_3072_4096_stub`. The encoding surface is
//! width-generic (slice-based PSS/OAEP and the already-slice-based
//! PKCS#1 v1.5 encoder), while the key struct, CRT sign path, and
//! Bellcore verify-after-sign logic are generated by the
//! `define_rsa_wide` macro from `rsa_wide_impl`.
//!
//! # Approved services
//!
//! | Service | Spec | Entry point |
//! |---------|------|-------------|
//! | RSASSA-PKCS1-v1_5 verify, SHA-256 | FIPS 186-5 §5.4 / RFC 8017 §8.2 | [`pkcs1_v15_verify`] |
//! | RSASSA-PKCS1-v1_5 sign, SHA-256   | FIPS 186-5 §5.4 / RFC 8017 §8.2 | [`RsaPrivateKey3072::sign_pkcs1_v15_sha256`] |
//! | RSASSA-PSS verify, SHA-256, MGF1  | FIPS 186-5 §5.4 / RFC 8017 §8.1 | [`pss_verify`] |
//! | RSASSA-PSS sign, SHA-256, MGF1    | FIPS 186-5 §5.4 / RFC 8017 §8.1 | [`RsaPrivateKey3072::sign_pss_sha256_with_salt`] |
//! | RSA key generation (3072-bit)     | FIPS 186-5 §A.1.1 / §B.3.1      | [`RsaPrivateKey3072::generate`] |
//! | RSAES-OAEP encrypt, SHA-256       | SP 800-56Br2 / RFC 8017 §7.1    | [`oaep_encrypt`] |
//! | RSAES-OAEP decrypt, SHA-256       | SP 800-56Br2 / RFC 8017 §7.1    | [`RsaPrivateKey3072::decrypt_oaep_sha256`] |
//!
//! # PSS parameters
//!
//! `emBits = 3071`, `emLen = 384`, `sLen = hLen = 32`. The top bit
//! of `maskedDB[0]` is cleared on encode and verified on decode,
//! identical to the RSA-2048 case.
//!
//! # OAEP parameters
//!
//! `k = 384`, `hLen = 32`, `DB_LEN = 351`, `MAX_MSG_LEN = 318`.
//!
//! # Side-channel posture
//!
//! Identical to RSA-2048 — `pow_secret` uses the constant-time 4-bit
//! windowed Montgomery ladder at the corresponding half-width
//! (`MontCtx1536`) and full-width (`MontCtx3072`). See the crate-level
//! docs for the full posture disclosure.
//!
//! # FIPS module gating
//!
//! All public service entry points route through
//! [`oxicrypt_module::require_operational`] and the appropriate
//! algorithm-profile check.

#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::similar_names,
    clippy::too_many_arguments,
    dead_code
)]

use crate::bigint1536::U1536;
use crate::bigint3072::U3072;
use crate::mont1536::MontCtx1536;
use crate::mont3072::MontCtx3072;

crate::rsa_wide_impl::define_rsa_wide! {
    full_type = U3072;
    full_bytes = 384;
    full_limbs = 48;
    full_mont = MontCtx3072;
    full_mod = crate::bigint3072;
    half_type = U1536;
    half_bytes = 192;
    half_limbs = 24;
    half_mont = MontCtx1536;
    half_reduce = crate::keygen3072::u3072_mod_u1536;
    keygen_fn = crate::keygen3072::generate_3072;
    keygen_km = KeyMaterial3072;
    nlen = 3072;
    em_bits = 3071;
    em_len = 384;
    oaep_k = 384;
    oaep_max_msg = 318;
    key_struct = RsaPrivateKey3072;
    crt_struct = CrtComponents3072;
    crt_raw = CrtComponentsRaw3072;
    svc_keygen = Service::RsaKeygen3072;
    svc_pkcs1_sign = Service::RsaPkcs1v15Sign3072;
    svc_pkcs1_verify = Service::RsaPkcs1v15Verify3072;
    svc_pss_sign = Service::RsaPssSign3072;
    svc_pss_verify = Service::RsaPssVerify3072;
    svc_oaep = Service::RsaOaep3072;
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic, clippy::expect_used)]
mod tests {
    use super::*;
    use oxicrypt_drbg::HmacDrbgSha256;

    /// Helper: set up module state for testing.
    fn init_module() {
        let _ = oxicrypt_module::initialize_with_tests(&[]);
    }

    #[test]
    fn pkcs1_v15_sign_verify_roundtrip() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0xA1u8; 48], &[0xB2u8; 24], b"rsa3072-test")
            .unwrap();
        let key = RsaPrivateKey3072::generate(&mut drbg, 65537).unwrap();
        let msg = b"rsa-3072 pkcs1v15 roundtrip";
        let sig = key.sign_pkcs1_v15_sha256(msg).unwrap();
        pkcs1_v15_verify(key.modulus_bytes(), key.public_exponent(), msg, &sig).unwrap();
    }

    #[test]
    fn pkcs1_v15_verify_rejects_tampered_sig() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0xC3u8; 48], &[0xD4u8; 24], b"rsa3072-tamper")
            .unwrap();
        let key = RsaPrivateKey3072::generate(&mut drbg, 65537).unwrap();
        let msg = b"tamper test 3072";
        let mut sig = key.sign_pkcs1_v15_sha256(msg).unwrap();
        sig[100] ^= 0x01;
        assert!(pkcs1_v15_verify(key.modulus_bytes(), key.public_exponent(), msg, &sig).is_err());
    }

    #[test]
    fn pss_sign_verify_roundtrip() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0xE5u8; 48], &[0xF6u8; 24], b"rsa3072-pss")
            .unwrap();
        let key = RsaPrivateKey3072::generate(&mut drbg, 65537).unwrap();
        let msg = b"rsa-3072 pss roundtrip";
        let salt = [0x77u8; 32];
        let sig = key.sign_pss_sha256_with_salt(msg, &salt).unwrap();
        pss_verify(key.modulus_bytes(), key.public_exponent(), msg, &sig).unwrap();
    }

    #[test]
    fn pss_verify_rejects_wrong_msg() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0x11u8; 48], &[0x22u8; 24], b"rsa3072-pss-bad")
            .unwrap();
        let key = RsaPrivateKey3072::generate(&mut drbg, 65537).unwrap();
        let salt = [0x33u8; 32];
        let sig = key.sign_pss_sha256_with_salt(b"original", &salt).unwrap();
        assert!(pss_verify(
            key.modulus_bytes(),
            key.public_exponent(),
            b"different",
            &sig
        )
        .is_err());
    }

    #[test]
    fn oaep_encrypt_decrypt_roundtrip() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0x44u8; 48], &[0x55u8; 24], b"rsa3072-oaep")
            .unwrap();
        let key = RsaPrivateKey3072::generate(&mut drbg, 65537).unwrap();
        let label = b"";
        let msg = b"hello OAEP 3072";
        let ct = oaep_encrypt(
            &mut drbg,
            key.modulus_bytes(),
            key.public_exponent(),
            label,
            msg,
        )
        .unwrap();
        let mut out = [0u8; OAEP_MAX_MSG_LEN];
        let mlen = key.decrypt_oaep_sha256(label, &ct, &mut out).unwrap();
        assert_eq!(&out[..mlen], msg);
    }

    #[test]
    fn oaep_rejects_wrong_label() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0x66u8; 48], &[0x77u8; 24], b"rsa3072-oaep-bad")
            .unwrap();
        let key = RsaPrivateKey3072::generate(&mut drbg, 65537).unwrap();
        let ct = oaep_encrypt(
            &mut drbg,
            key.modulus_bytes(),
            key.public_exponent(),
            b"right",
            b"msg",
        )
        .unwrap();
        let mut out = [0u8; OAEP_MAX_MSG_LEN];
        assert!(key.decrypt_oaep_sha256(b"wrong", &ct, &mut out).is_err());
    }

    #[test]
    fn from_components_pct_catches_mismatch() {
        init_module();
        // A random 384-byte "modulus" won't produce a valid RSA key.
        let bad_n = [0xffu8; MODULUS_BYTES];
        let bad_d = [0x01u8; MODULUS_BYTES];
        assert!(RsaPrivateKey3072::from_components(&bad_n, 65537, &bad_d).is_err());
    }
}
