//! RSA-4096 key operations — sign, verify, encrypt, decrypt, keygen.
//!
//! Full implementation of the RSA-4096 service layer, replacing the
//! earlier stubs in `rsa_3072_4096_stub`. Generated by the same
//! `define_rsa_wide` macro that produces RSA-3072 in [`crate::rsa3072`].
//!
//! # Approved services
//!
//! | Service | Spec | Entry point |
//! |---------|------|-------------|
//! | RSASSA-PKCS1-v1_5 verify, SHA-256 | FIPS 186-5 §5.4 / RFC 8017 §8.2 | [`pkcs1_v15_verify`] |
//! | RSASSA-PKCS1-v1_5 sign, SHA-256   | FIPS 186-5 §5.4 / RFC 8017 §8.2 | [`RsaPrivateKey4096::sign_pkcs1_v15_sha256`] |
//! | RSASSA-PSS verify, SHA-256, MGF1  | FIPS 186-5 §5.4 / RFC 8017 §8.1 | [`pss_verify`] |
//! | RSASSA-PSS sign, SHA-256, MGF1    | FIPS 186-5 §5.4 / RFC 8017 §8.1 | [`RsaPrivateKey4096::sign_pss_sha256_with_salt`] |
//! | RSA key generation (4096-bit)     | FIPS 186-5 §A.1.1 / §B.3.1      | [`RsaPrivateKey4096::generate`] |
//! | RSAES-OAEP encrypt, SHA-256       | SP 800-56Br2 / RFC 8017 §7.1    | [`oaep_encrypt`] |
//! | RSAES-OAEP decrypt, SHA-256       | SP 800-56Br2 / RFC 8017 §7.1    | [`RsaPrivateKey4096::decrypt_oaep_sha256`] |
//!
//! # PSS parameters
//!
//! `emBits = 4095`, `emLen = 512`, `sLen = hLen = 32`.
//!
//! # OAEP parameters
//!
//! `k = 512`, `hLen = 32`, `DB_LEN = 479`, `MAX_MSG_LEN = 446`.
//!
//! # Side-channel posture
//!
//! Identical to RSA-2048 / RSA-3072 — `pow_secret` uses the
//! constant-time 4-bit windowed Montgomery ladder at half-width
//! (`MontCtx2048`) and full-width (`MontCtx4096`).

#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::similar_names,
    clippy::too_many_arguments,
    dead_code
)]

use crate::bigint2048::U2048;
use crate::bigint4096::U4096;
use crate::mont2048::MontCtx2048;
use crate::mont4096::MontCtx4096;

crate::rsa_wide_impl::define_rsa_wide! {
    full_type = U4096;
    full_bytes = 512;
    full_limbs = 64;
    full_mont = MontCtx4096;
    full_mod = crate::bigint4096;
    half_type = U2048;
    half_bytes = 256;
    half_limbs = 32;
    half_mont = MontCtx2048;
    half_reduce = crate::keygen4096::u4096_mod_u2048;
    keygen_fn = crate::keygen4096::generate_4096;
    keygen_km = KeyMaterial4096;
    nlen = 4096;
    em_bits = 4095;
    em_len = 512;
    oaep_k = 512;
    oaep_max_msg = 446;
    key_struct = RsaPrivateKey4096;
    crt_struct = CrtComponents4096;
    crt_raw = CrtComponentsRaw4096;
    svc_keygen = Service::RsaKeygen4096;
    svc_pkcs1_sign = Service::RsaPkcs1v15Sign4096;
    svc_pkcs1_verify = Service::RsaPkcs1v15Verify4096;
    svc_pss_sign = Service::RsaPssSign4096;
    svc_pss_verify = Service::RsaPssVerify4096;
    svc_oaep = Service::RsaOaep4096;
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic, clippy::expect_used)]
mod tests {
    use super::*;
    use oxicrypt_drbg::HmacDrbgSha256;

    fn init_module() {
        let _ = oxicrypt_module::initialize_with_tests(&[]);
    }

    #[test]
    fn pkcs1_v15_sign_verify_roundtrip() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0xA1u8; 48], &[0xB2u8; 24], b"rsa4096-test")
            .unwrap();
        let key = RsaPrivateKey4096::generate(&mut drbg, 65537).unwrap();
        let msg = b"rsa-4096 pkcs1v15 roundtrip";
        let sig = key.sign_pkcs1_v15_sha256(msg).unwrap();
        pkcs1_v15_verify(key.modulus_bytes(), key.public_exponent(), msg, &sig).unwrap();
    }

    #[test]
    fn pkcs1_v15_verify_rejects_tampered_sig() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0xC3u8; 48], &[0xD4u8; 24], b"rsa4096-tamper")
            .unwrap();
        let key = RsaPrivateKey4096::generate(&mut drbg, 65537).unwrap();
        let msg = b"tamper test 4096";
        let mut sig = key.sign_pkcs1_v15_sha256(msg).unwrap();
        sig[200] ^= 0x01;
        assert!(pkcs1_v15_verify(key.modulus_bytes(), key.public_exponent(), msg, &sig).is_err());
    }

    #[test]
    fn pss_sign_verify_roundtrip() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0xE5u8; 48], &[0xF6u8; 24], b"rsa4096-pss")
            .unwrap();
        let key = RsaPrivateKey4096::generate(&mut drbg, 65537).unwrap();
        let msg = b"rsa-4096 pss roundtrip";
        let salt = [0x88u8; 32];
        let sig = key.sign_pss_sha256_with_salt(msg, &salt).unwrap();
        pss_verify(key.modulus_bytes(), key.public_exponent(), msg, &sig).unwrap();
    }

    #[test]
    fn pss_verify_rejects_wrong_msg() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0x11u8; 48], &[0x22u8; 24], b"rsa4096-pss-bad")
            .unwrap();
        let key = RsaPrivateKey4096::generate(&mut drbg, 65537).unwrap();
        let salt = [0x44u8; 32];
        let sig = key.sign_pss_sha256_with_salt(b"original", &salt).unwrap();
        assert!(
            pss_verify(
                key.modulus_bytes(),
                key.public_exponent(),
                b"different",
                &sig
            )
            .is_err()
        );
    }

    #[test]
    fn oaep_encrypt_decrypt_roundtrip() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0x55u8; 48], &[0x66u8; 24], b"rsa4096-oaep")
            .unwrap();
        let key = RsaPrivateKey4096::generate(&mut drbg, 65537).unwrap();
        let label = b"";
        let msg = b"hello OAEP 4096";
        let ct = oaep_encrypt(
            &mut drbg,
            key.modulus_bytes(),
            key.public_exponent(),
            label,
            msg,
        )
        .unwrap();
        let mut out = [0u8; OAEP_MAX_MSG_LEN];
        let mlen = key.decrypt_oaep_sha256(label, &ct, &mut out).unwrap();
        assert_eq!(&out[..mlen], msg);
    }

    #[test]
    fn oaep_rejects_wrong_label() {
        init_module();
        let mut drbg = HmacDrbgSha256::new();
        drbg.instantiate(&[0x77u8; 48], &[0x88u8; 24], b"rsa4096-oaep-bad")
            .unwrap();
        let key = RsaPrivateKey4096::generate(&mut drbg, 65537).unwrap();
        let ct = oaep_encrypt(
            &mut drbg,
            key.modulus_bytes(),
            key.public_exponent(),
            b"right",
            b"msg",
        )
        .unwrap();
        let mut out = [0u8; OAEP_MAX_MSG_LEN];
        assert!(key.decrypt_oaep_sha256(b"wrong", &ct, &mut out).is_err());
    }

    #[test]
    fn from_components_pct_catches_mismatch() {
        init_module();
        let bad_n = [0xffu8; MODULUS_BYTES];
        let bad_d = [0x01u8; MODULUS_BYTES];
        assert!(RsaPrivateKey4096::from_components(&bad_n, 65537, &bad_d).is_err());
    }
}
