[package]
name = "oxicrypt-ecdh"
description = "ECDH per SP 800-56Ar3"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
oxicrypt-ecdsa = { path = "../oxicrypt-ecdsa" }
oxicrypt-module = { path = "../oxicrypt-module" }

[dev-dependencies]
oxicrypt-drbg = { path = "../oxicrypt-drbg" }
