[package]
name = "fips-drbg"
description = "CTR_DRBG, HMAC_DRBG, Hash_DRBG per SP 800-90Ar1"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
fips-module = { path = "../fips-module" }
fips-aes = { path = "../fips-aes" }
fips-sha = { path = "../fips-sha" }
