[package]
name = "oxicrypt-hmac"
description = "HMAC for all approved SHA variants per FIPS 198-1"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
oxicrypt-module = { path = "../oxicrypt-module" }
oxicrypt-sha = { path = "../oxicrypt-sha" }
oxicrypt-test-vectors = { path = "../oxicrypt-test-vectors" }
oxicrypt-zeroize = { path = "../oxicrypt-zeroize" }
