//! ML-DSA-44 instantiation (FIPS 204 §4 Table 1).
//!
//! Parameters: λ=128, τ=39, γ₁=2¹⁷, γ₂=(q−1)/88, k=4, ℓ=4, η=2, β=78, ω=80.
//! Sizes: PK_LEN=1312, SK_LEN=2560, SIG_LEN=2420, CTILDE_LEN=32.
//!
//! Generated by the [`ml_dsa_impl!`](crate::ml_dsa_impl) macro.
//!
//! # KAT seeds
//!
//! Seeds are fresh deterministic constants distinct from the
//! ML-DSA-65 / ML-DSA-87 seeds; the self-test exercises a generic
//! round-trip + tamper oracle that holds over the entire seed space.
//!
//! # CNSA gating
//!
//! ML-DSA-44 is **not** part of CNSA 2.0 (which mandates ML-DSA-87)
//! and is **not** in the CNSA 1.0 transition allow-list. The
//! [`Service::MlDsa44Sign`] / `Verify` / `Keygen` variants are
//! permitted only under [`oxicrypt_module::AlgorithmProfile::Unrestricted`].
//! See `crates/oxicrypt-module/src/lib.rs` `is_cnsa1_allowed` and
//! `is_cnsa2_allowed` — neither extends to ML-DSA-44.

#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::cast_lossless,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::similar_names,
    clippy::many_single_char_names,
    clippy::needless_range_loop,
    clippy::integer_division,
    clippy::too_many_lines,
    dead_code
)]

crate::ml_dsa_impl::ml_dsa_impl! {
    lambda = 128;
    tau = 39;
    gamma1 = 1 << 17;
    gamma2 = (8_380_417 - 1) / 88;
    k = 4;
    l = 4;
    eta = 2;
    beta = 78;
    omega = 80;
    svc_keygen = Service::MlDsa44Keygen;
    svc_sign = Service::MlDsa44Sign;
    svc_verify = Service::MlDsa44Verify;
    // KAT seed: fresh deterministic 32-byte constant.
    kat_xi = [
        0x44, 0x05, 0x14, 0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0, 0x11, 0x22, 0x33, 0x44,
        0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x01, 0x23, 0x45, 0x67,
        0x89, 0xab,
    ];
    kat_msg = b"ML-DSA-44 self-test message for FIPS 204 compliance";
    kat_name = "ML-DSA-44 KAT (keygen + sign + verify round-trip, FIPS 204)";
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]
mod tests {
    use super::*;

    #[test]
    fn self_test_passes() {
        self_test().unwrap();
    }

    #[test]
    fn key_sizes_match_spec() {
        assert_eq!(PK_LEN, 1312);
        assert_eq!(SK_LEN, 2560);
        assert_eq!(SIG_LEN, 2420);
        assert_eq!(CTILDE_LEN, 32);
    }

    #[test]
    fn parameter_constants_match_spec() {
        assert_eq!(K, 4);
        assert_eq!(L, 4);
        assert_eq!(ETA, 2);
        assert_eq!(TAU, 39);
        assert_eq!(BETA, 78);
        assert_eq!(OMEGA, 80);
    }

    #[test]
    fn round_trip_basic() {
        let xi = [0x42u8; 32];
        let (pk, sk) = keygen_internal(&xi);
        let msg = b"hello, ML-DSA-44";
        let sig = sign_internal(&sk, msg).unwrap();
        assert!(verify_internal(&pk, msg, &sig));
    }

    #[test]
    fn wrong_message_rejected() {
        let xi = [0x01u8; 32];
        let (pk, sk) = keygen_internal(&xi);
        let sig = sign_internal(&sk, b"original").unwrap();
        assert!(!verify_internal(&pk, b"tampered", &sig));
    }

    #[test]
    fn tampered_signature_rejected() {
        let xi = [0x55u8; 32];
        let (pk, sk) = keygen_internal(&xi);
        let msg = b"test message";
        let mut sig = sign_internal(&sk, msg).unwrap();
        sig[50] ^= 0xFF;
        assert!(!verify_internal(&pk, msg, &sig));
    }
}
