//! ML-DSA-65 instantiation (FIPS 204 §4 Table 1).
//!
//! Parameters: λ=192, τ=49, γ₁=2¹⁹, γ₂=(q−1)/32, k=6, ℓ=5, η=4, β=196, ω=55.
//! Sizes: PK_LEN=1952, SK_LEN=4032, SIG_LEN=3309, CTILDE_LEN=48.
//!
//! Generated by the [`ml_dsa_impl!`](crate::ml_dsa_impl) macro.
//!
//! # KAT seeds
//!
//! Seeds are fresh deterministic constants distinct from the
//! ML-DSA-44 / ML-DSA-87 seeds; the self-test exercises a generic
//! round-trip + tamper oracle that holds over the entire seed space.
//!
//! # CNSA gating
//!
//! ML-DSA-65 is **not** part of CNSA 2.0 (which mandates ML-DSA-87)
//! and is **not** in the CNSA 1.0 transition allow-list. The
//! [`Service::MlDsa65Sign`] / `Verify` / `Keygen` variants are
//! permitted only under [`oxicrypt_module::AlgorithmProfile::Unrestricted`].
//! See `crates/oxicrypt-module/src/lib.rs` `is_cnsa1_allowed` and
//! `is_cnsa2_allowed` — neither extends to ML-DSA-65.

#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::cast_lossless,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::similar_names,
    clippy::many_single_char_names,
    clippy::needless_range_loop,
    clippy::integer_division,
    clippy::too_many_lines,
    dead_code
)]

crate::ml_dsa_impl::ml_dsa_impl! {
    lambda = 192;
    tau = 49;
    gamma1 = 1 << 19;
    gamma2 = (8_380_417 - 1) / 32;
    k = 6;
    l = 5;
    eta = 4;
    beta = 196;
    omega = 55;
    svc_keygen = Service::MlDsa65Keygen;
    svc_sign = Service::MlDsa65Sign;
    svc_verify = Service::MlDsa65Verify;
    // KAT seed: fresh deterministic 32-byte constant.
    kat_xi = [
        0x65, 0x05, 0x14, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10, 0xef, 0xcd, 0xab, 0x89,
        0x67, 0x45, 0x23, 0x01, 0x89, 0xab, 0xcd, 0xef, 0x10, 0x32, 0x54, 0x76, 0x98, 0xba, 0xdc,
        0xfe, 0x21,
    ];
    kat_msg = b"ML-DSA-65 self-test message for FIPS 204 compliance";
    kat_name = "ML-DSA-65 KAT (keygen + sign + verify round-trip, FIPS 204)";
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]
mod tests {
    use super::*;

    #[test]
    fn self_test_passes() {
        self_test().unwrap();
    }

    #[test]
    fn key_sizes_match_spec() {
        assert_eq!(PK_LEN, 1952);
        assert_eq!(SK_LEN, 4032);
        assert_eq!(SIG_LEN, 3309);
        assert_eq!(CTILDE_LEN, 48);
    }

    #[test]
    fn parameter_constants_match_spec() {
        assert_eq!(K, 6);
        assert_eq!(L, 5);
        assert_eq!(ETA, 4);
        assert_eq!(TAU, 49);
        assert_eq!(BETA, 196);
        assert_eq!(OMEGA, 55);
    }

    #[test]
    fn round_trip_basic() {
        let xi = [0x42u8; 32];
        let (pk, sk) = keygen_internal(&xi);
        let msg = b"hello, ML-DSA-65";
        let sig = sign_internal(&sk, msg).unwrap();
        assert!(verify_internal(&pk, msg, &sig));
    }

    #[test]
    fn wrong_message_rejected() {
        let xi = [0x01u8; 32];
        let (pk, sk) = keygen_internal(&xi);
        let sig = sign_internal(&sk, b"original").unwrap();
        assert!(!verify_internal(&pk, b"tampered", &sig));
    }

    #[test]
    fn tampered_signature_rejected() {
        let xi = [0x55u8; 32];
        let (pk, sk) = keygen_internal(&xi);
        let msg = b"test message";
        let mut sig = sign_internal(&sk, msg).unwrap();
        sig[50] ^= 0xFF;
        assert!(!verify_internal(&pk, msg, &sig));
    }
}
